<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Ações',
    'Active' => 'Ativo',
    'Add Book' => 'Adicionar Livro',
    'All' => 'Todos',
    'Are you sure to delete this {item}?' => 'Você tem certeza de que deseja excluir esse {item}?',
    'Book Listing' => 'Listagem dos Livros',
    'CSV' => 'CSV',
    'Clear selection' => 'Limpar seleção',
    'Collapse' => 'Contrair',
    'Collapse All' => 'Contrair Todos',
    'Comma Separated Values' => 'Valores Separados por Vírgula',
    'Delete' => 'Excluir',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Desative todos os bloqueadores de popup do navegador para fazer o download',
    'Download Selected' => 'Baixar Selecionados',
    'Excel' => 'Excel',
    'Expand' => 'Expandir',
    'Expand All' => 'Expandir Todos',
    'Export' => 'Exportar',
    'Export All Data' => 'Exportar Todos os Registros',
    'Export Page Data' => 'Exportar os Registros dessa Página',
    'ExportWorksheet' => 'ExportarPlanilha',
    'Failed to update editable data due to an unknown server error' => 'Falha ao atualizar o campo editável causada por um erro desconhecido no servidor',
    'Generated' => 'Gerado',
    'Generating the export file. Please wait...' => 'Gerando o arquivo de exportação. Aguarde...',
    'Grid Export' => 'Exportar Listagem',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'Hyper Text Markup Language',
    'Inactive' => 'Inativo',
    'Invalid editable index or model form name' => 'Índice ou nome do model inválidos',
    'Invalid or bad editable data' => 'Dado editável inválido ou com problemas',
    'JSON' => 'JSON',
    'JavaScript Object Notation' => 'Notação de Objetos JavaScript',
    'Krajee Solutions' => 'Krajee Soluções',
    'Krajee Yii2 Grid Export Extension' => 'Extensão Krajee Yii2 Grid Export',
    'Library' => 'Biblioteca',
    'Microsoft Excel 95+' => 'Microsoft Excel 95+',
    'No data found' => 'Nenhum registro encontrado',
    'No valid editable model found' => 'Nenhum modelo editável válido foi encontrado',
    'Ok to proceed?' => 'Ok para prosseguir?',
    'PDF' => 'PDF',
    'PDF export generated by kartik-v/yii2-grid extension' => 'Exportação de PDF gerado por kartik-v/yii2-grid extension',
    'Page' => 'Página',
    'Portable Document Format' => 'Portable Document Format',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Solicitação enviada! Depois de salvar o arquivo você poderá fechar essa janela.',
    'Reset Grid' => 'Redefinir Listagem',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Redimensione as colunas da tabela como em uma planilha, arrastando a borda da coluna.',
    'Show all data' => 'Exibir todos os registros',
    'Show first page data' => 'Exibir os registros da primeira página',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.' => 'Exibindo <b>{begin, number}-{end, number}</b> de <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.',
    'Tab Delimited Text' => 'Texto Delimitado por Tabulação',
    'Text' => 'Texto',
    'The CSV export file will be generated for download.' => 'O arquivo de exportação CSV será gerado para download.',
    'The EXCEL export file will be generated for download.' => 'O arquivo de exportação EXCEL será gerado para download.',
    'The HTML export file will be generated for download.' => 'O arquivo de exportação HTML será gerado para download.',
    'The JSON export file will be generated for download.' => 'O arquivo de exportação JSON será gerado para download.',
    'The PDF export file will be generated for download.' => 'O arquivo de exportação PDF será gerado para download.',
    'The TEXT export file will be generated for download.' => 'O arquivo de exportação TEXTO será gerado para download.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'O resumo da página exibe a SOMA dos valores das primeiras 3 colunas e a MÉDIA da última coluna.',
    'The table header sticks to the top in this demo as you scroll' => 'O cabeçalho da tabela adere ao topo nesta demonstração enquanto você rola a página',
    'There are {totalCount} records. Are you sure you want to display them all?' => 'Existem {totalCount} registros. Você tem certeza de que deseja exibir todos?',
    'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => 'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.',
    'Update' => 'Alterar',
    'View' => 'Exibir',
    'Yii2 Grid Export (PDF)' => 'Yii2 Grid Export (PDF)',
    'export' => 'exportar',
    'grid-export' => 'exportar-listagem',
    'item' => 'item',
    'items' => 'itens',
    'items-few' => 'poucos itens',
    'items-many' => 'muitos itens',
    'krajee, grid, export, yii2-grid, pdf' => 'krajee, grid, export, yii2-grid, pdf',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Extensões',
    '<small>Loading &hellip;</small>' => '',
    'items-acc' => '',
];
