<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Aktionen',
    'Active' => 'Aktiv',
    'Add Book' => 'Neues Buch',
    'All' => 'Alle',
    'Are you sure to delete this {item}?' => 'Wollen Sie dieses {item} wirklich löschen?',
    'Book Listing' => 'Liste der Bücher',
    'CSV' => 'CSV',
    'Clear selection' => 'Auswahl entfernen',
    'Collapse' => 'Einklappen',
    'Collapse All' => 'Alle einklappen',
    'Comma Separated Values' => 'Komma-getrennte Werte',
    'Delete' => 'Löschen',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Deaktivieren Sie den Popup-Blocker in Ihrem Browser damit der Download funktioniert.',
    'Download Selected' => 'Markierte herunterladen',
    'Excel' => 'Excel',
    'Expand' => 'Ausklappen',
    'Expand All' => 'Alle ausklappen',
    'Export' => 'Export',
    'Export All Data' => 'Alle Daten exportieren',
    'Export Page Data' => 'Seiten-Daten exportieren',
    'ExportWorksheet' => 'ExportArbeitsblatt',
    'Failed to update editable data due to an unknown server error' => 'Fehler beim Aktualisieren der Daten aufgrund eines unbekannten Serverfehlers',
    'Generated' => 'Erstellt',
    'Generating the export file. Please wait...' => 'Erstelle die Export-Datei. Bitte warten...',
    'Grid Export' => 'Tabellen Export',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'Hyper Text Markup Language',
    'Inactive' => 'Inaktiv',
    'Invalid editable index or model form name' => 'Ungültiger Index oder Formularname',
    'Invalid or bad editable data' => 'Ungültige oder fehlerhafte Daten',
    'JSON' => 'JSON',
    'JavaScript Object Notation' => 'JavaScript Objektnotation',
    'Library' => 'Bibliothek',
    'Microsoft Excel 95+' => 'Microsoft Excel 95+',
    'No data found' => 'Keine Daten gefunden',
    'No valid editable model found' => 'Kein gültiges zu bearbeitendes Modell gefunden',
    'Ok to proceed?' => 'Fortfahren?',
    'PDF' => 'PDF',
    'PDF export generated by kartik-v/yii2-grid extension' => 'PDF-Export generiert durch kartik-v/yii2-grid-extension',
    'Page' => 'Seite',
    'Portable Document Format' => 'Plattformunabhängiges Dateiformat',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Anfrage übermittelt! Sie können diesen Dialog schließen, nachdem Sie die Datei gespeichert haben.',
    'Reset Grid' => 'Tabelle zurücksetzen',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Ändern Sie die Größe von Tabellenspalten genau wie in einer Tabellenkalkulation, indem Sie die Spaltenränder verschieben.',
    'Select...' => '',
    'Show all data' => 'Alle Daten anzeigen',
    'Show first page data' => 'Daten der ersten Seite anzeigen',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.' => 'Zeige <b>{begin, number}-{end, number}</b> von <b>{totalCount, number}</b> {totalCount, plural, one{{item}} few{{items-acc}} many{{items-acc}} other{{items-acc}}}.',
    'Tab Delimited Text' => 'Tabulatorgetrennter Text',
    'Text' => 'Text',
    'The CSV export file will be generated for download.' => 'Die CSV-Export-Datei wird für den Download erstellt.',
    'The EXCEL export file will be generated for download.' => 'Die Excel-Export-Datei wird für den Download erstellt.',
    'The HTML export file will be generated for download.' => 'Die HTML-Export-Datei wird für den Download erstellt.',
    'The JSON export file will be generated for download.' => 'Die JSON-Export-Datei wird für den Download erstellt.',
    'The PDF export file will be generated for download.' => 'Die PDF-Export-Datei wird für den Download erstellt.',
    'The TEXT export file will be generated for download.' => 'Die Text-Export-Datei wird für den Download erstellt.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Die Seite Zusammenfassung wird SUM für die ersten drei und AVG für die letzte Spalte anzeigen.',
    'The table header sticks to the top in this demo as you scroll' => 'Wenn Sie scrollen, hält sich der Tabellenkopf an der Oberkante der Demoseite.',
    'There are {totalCount} records. Are you sure you want to display them all?' => 'Es gibt insgesamt {totalCount} Einträge. Wollen Sie alle anzeigen?',
    'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => 'Insgesamt <b>{count, number}</b> {count, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'Update' => 'Bearbeitung',
    'View' => 'Anzeige',
    'Yii2 Grid Export (PDF)' => 'Yii2 Grid Export (PDF)',
    'export' => 'exportieren',
    'grid-export' => 'grid-export',
    'item' => 'Eintrag',
    'items' => 'Einträge',
    'items-acc' => 'Einträgen',
    'items-few' => 'Einträge',
    'items-many' => 'Einträge',
    'krajee, grid, export, yii2-grid, pdf' => 'krajee, gitter, export, yii2-grid, pdf',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Erweiterungen',
    '<small>Loading &hellip;</small>' => '',
    'Krajee Solutions' => '',
    'Krajee Yii2 Grid Export Extension' => '',
];
