<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.' => 'Намойиш этилаябди <b>{begin, number}-{end, number}</b> та ёзув <b>{totalCount, number}</b> {totalCount, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => 'Жами <b>{count, number}</b> {count, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'item' => 'қайд',
    'items' => 'ёзув',
    'items-few' => 'ёзув',
    'items-many' => 'ёзув',
    '<small>Loading &hellip;</small>' => '<small>Юкланмоқда &hellip;</small>',
    'Actions' => 'Аммалар',
    'Active' => 'Фаол',
    'Add Book' => 'Янги қўшиш',
    'All' => 'Ҳаммаси',
    'Are you sure to delete this {item}?' => '{item}ни ўчириб ташлашингизга ишончингиз комилми?',
    'Book Listing' => 'Китоб рўйхати',
    'CSV' => '',
    'Clear selection' => 'Танланганларни бекор қилиш',
    'Collapse' => 'Йиғиш',
    'Collapse All' => 'Барчасини йиғиш',
    'Comma Separated Values' => 'Вергул билан ажратилган қийматлар',
    'Delete' => 'Ўчириш',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Юклаб олиш учун ажралиб чиқувчи ойна блокловчини ўчиринг.',
    'Download Selected' => 'Танланганларни юклаб олиш',
    'Excel' => '',
    'Expand' => 'Кенгайтириш',
    'Expand All' => 'Ҳаммасини кенгайтириш',
    'Export' => 'Экспорт',
    'Export All Data' => 'Ҳамма маълумотни экспорт қилиш',
    'Export Page Data' => 'Саҳифадаги маълумотни экспорт қилиш',
    'ExportWorksheet' => '',
    'Failed to update editable data due to an unknown server error' => 'Номаълум сервер хатоси туфайли таҳрирланадиган маълумотларни янгилаб бўлмади',
    'Generated' => 'Ҳосил қилинди',
    'Generating the export file. Please wait...' => 'Файл ҳосил қилинмоқда. Илтимос, кутинг',
    'Grid Export' => 'Экспорт',
    'HTML' => '',
    'Hyper Text Markup Language' => 'Гипер матнли маркерлаш тили',
    'Inactive' => 'Фаол эмас',
    'Invalid editable index or model form name' => 'Ўзгартириш индекси ёки модель форма номи нотўғри',
    'Invalid or bad editable data' => 'Ўзгаритиш маълумоти нотўғри',
    'JSON' => '',
    'JavaScript Object Notation' => 'JavaScript объект белгиси',
    'Krajee Solutions' => '',
    'Krajee Yii2 Grid Export Extension' => '',
    'Library' => 'Кутубхона',
    'Microsoft Excel 95+' => '',
    'No data found' => 'Маълумот топилмади',
    'No valid editable model found' => 'Ўзгартириш модели нотўғри',
    'Ok to proceed?' => 'Давом этиш учун ОК тугмасини босинг',
    'PDF' => '',
    'PDF export generated by kartik-v/yii2-grid extension' => 'PDF kartik-v/yii2-grid кенгайтмаси томонидан яратилган',
    'Page' => 'Саҳифа',
    'Portable Document Format' => 'Кўчма ҳужжат формати',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Сўров юборилди! Файлни сақлаганингиздан кейин ушбу диалог ойнасини ёпишингиз мумкин',
    'Reset Grid' => 'Жадвални тозалаш',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Устун чеккаларини ушлаб, жадвал устунларининг ўлчамларини худди электрон жадвал каби ўзгартиринг',
    'Select...' => 'Танланг...',
    'Show all data' => 'Ҳамма маълумотни кўрсатиш',
    'Show first page data' => 'Биринчи саҳифадаги маълумотни кўрсатиш',
    'Tab Delimited Text' => 'Tab билан ажратилган матн',
    'Text' => 'Матн',
    'The CSV export file will be generated for download.' => 'CSV экспорт файли юклаб олиш учун яратилади',
    'The EXCEL export file will be generated for download.' => 'EXCEL экспорт файли юклаб олиш учун яратилади',
    'The HTML export file will be generated for download.' => 'HTML экспорт файли юклаб олиш учун яратилади',
    'The JSON export file will be generated for download.' => 'JSON экспорт файли юклаб олиш учун яратилади',
    'The PDF export file will be generated for download.' => 'PDF экспорт файли юклаб олиш учун яратилади',
    'The TEXT export file will be generated for download.' => 'TEXT экспорт файли юклаб олиш учун яратилади',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Саҳифа остида дастлабки 3 та устуни учун йиғинди, охиргиси учун ўртача қиймат кўрсатилади',
    'The table header sticks to the top in this demo as you scroll' => 'Ушбу демода жадвал сарлавҳаси айланаётганда юқорига ёпишади',
    'There are {totalCount} records. Are you sure you want to display them all?' => '{totalCount} та ёзув мавжуд. Ҳақиқатан ҳам уларнинг барчасини кўрсатмоқчимисиз?',
    'Update' => 'Таҳрирлаш',
    'View' => 'Кўриш',
    'Yii2 Grid Export (PDF)' => '',
    'export' => '',
    'grid-export' => '',
    'items-acc' => '',
    'krajee, grid, export, yii2-grid, pdf' => '',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Кенгайтмалари',
];
