<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'عملیات',
    'Active' => 'فعال',
    'Add Book' => 'افزودن کتاب',
    'All' => 'همه موارد',
    'Are you sure to delete this item?' => 'آیا از حذف این آیتم اطمینان دارید؟',
    'Book Listing' => 'لیست کتابها',
    'CSV' => 'CVS',
    'Clear selection' => 'پاک کردن انتخاب ها',
    'Collapse' => 'جمع کردن',
    'Collapse All' => 'جمع کردن همه موارد',
    'Comma Separated Values' => 'مقادیر جدا شده به وسیله کاما',
    'Delete' => 'حذف',
    'Disable any popup blockers in your browser to ensure proper download.' => 'برای اطمینان از صحت دانلود، مسدود کننده پاپ آپ مرورگر خود را غیر فعال کنید.',
    'Download Selected' => 'دانلود منتخب ها',
    'Excel' => 'اکسل',
    'Expand' => 'گسترش',
    'Expand All' => 'گسترش همه موارد',
    'Export' => 'خروجی',
    'Export All Data' => 'خروجی همه  داده ها',
    'Export Page Data' => 'خروجی داده های صفحه',
    'ExportWorksheet' => '',
    'Generated' => 'تولید شد',
    'Generating the export file. Please wait...' => 'در حال تولید فایل خروجی. لطفا منتظر باشید',
    'Grid Export' => 'خروجی گرید',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Inactive' => 'غیرفعال',
    'JSON' => '',
    'JavaScript Object Notation' => '',
    'Library' => 'کتابخانه',
    'Microsoft Excel 95+' => '',
    'No data found' => 'داده ای پیدا نشد',
    'Ok to proceed?' => '',
    'PDF' => '',
    'PDF export generated by kartik-v/yii2-grid extension' => '',
    'Page' => '',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => '',
    'Reset Grid' => '',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => '',
    'Show all data' => '',
    'Show first page data' => '',
    'Tab Delimited Text' => '',
    'Text' => '',
    'The CSV export file will be generated for download.' => '',
    'The EXCEL export file will be generated for download.' => '',
    'The HTML export file will be generated for download.' => '',
    'The JSON export file will be generated for download.' => '',
    'The PDF export file will be generated for download.' => '',
    'The TEXT export file will be generated for download.' => '',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => '',
    'The table header sticks to the top in this demo as you scroll' => '',
    'Update' => '',
    'View' => '',
    'Yii2 Grid Export (PDF)' => '',
    'export' => '',
    'grid-export' => '',
    'krajee, grid, export, yii2-grid, pdf' => '',
    '© Krajee Yii2 Extensions' => '',
];
