<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'HTML' => 'HTML',
    'CSV' => 'CSV',
    'Text' => 'Text',
    'Excel' => 'Excel',
    'Save as HTML' => 'Als HTML speichern',
    'Save as CSV' => 'Als CSV speichern',
    'Save as Text' => 'Als Text speichern',
    'Save as Excel' => 'Als Excel speichern',
    'Active' => 'Aktiv',
    'Inactive' => 'Inaktiv',
    'Actions' => 'Aktionen',
    'Export' => 'Exportieren',
    'export' => '',
    'grid-export' => '',
    'The HTML export file will be generated for download.' => 'Die HTML Export Datei wird für den Download erstellt.',
    'The CSV export file will be generated for download.' => 'Die CSV Export Datei wird für den Download erstellt.',
    'The TEXT export file will be generated for download.' => 'Die Text Export Datei wird für den Download erstellt.',
    'The EXCEL export file will be generated for download.' => 'Die Excel Export Datei wird für den Download erstellt.',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Deaktiviere den Popup Blocker in deinem Browser damit der Download funktioniert.',
    'No data found' => 'Keine Daten gefunden',
    // Demo data
    'Library' => 'Bibliothek',
    'Book Listing' => 'buchen Listing',
    'Add Book' => 'Neues Buch',
    'Reset Grid' => 'zurücksetzen Grid',
    'Download Selected' => 'Download markierte',
    'The table header sticks to the top in this demo as you scroll' => 'Der Tabellenkopf hält sich an der Spitze in dieser Demo, wie Sie blättern',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Die Seite Zusammenfassung wird SUM für ersten 3 Spalten Menge und AVG für die letzte.'
];
