<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => '动作',
    'Active' => '已激活',
    'Add Book' => '新增书籍',
    'All' => '全部',
    'Are you sure to delete this item?' => '确定删除此记录?',
    'Book Listing' => '书籍列表',
    'CSV' => 'CSV',
    'Clear selection' => '',
    'Collapse All' => '全部收起',
    'Collapse' => '收起',
    'Comma Separated Values' => '以逗号分割的值',
    'Delete' => '删除',
    'Disable any popup blockers in your browser to ensure proper download.' => '禁用所有阻止弹出窗口的浏览器设置来确保下载成功',
    'Download Selected' => '已选择下载项',
    'Excel' => 'Excel',
    'Expand All' => '全部展开',
    'Expand' => '展开',
    'Export All Data' => '导出所有数据',
    'Export Page Data' => '导出当前页数据',
    'Export' => '导出',
    'ExportWorksheet' => '导出工作表',
    'Generated' => '已经生成',
    'Generating the export file. Please wait...' => '正在导出文件,请稍后...',
    'Grid Export' => '导出表格',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => '超文本标记语言',
    'Inactive' => '未激活',
    'Invalid editable index or model form name' => '',
    'Invalid or bad editable data' => '',
    'JSON' => 'JSON',
    'JavaScript Object Notation' => 'JavaScript对象符号',
    'Library' => '类库',
    'Microsoft Excel 95+' => '微软Excel版本95以上',
    'No data found' => '未找到数据',
    'No valid editable model found' => '',
    'Ok to proceed?' => '确定执行操作?',
    'PDF export generated by kartik-v/yii2-grid extension' => '导出由kartik-v/yii2-grid扩展生成的PDF',
    'PDF' => 'PDF',
    'Page' => '页',
    'Portable Document Format' => '便携的文档格式',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => '请求已经提交,你可以在文件下载成功后关闭此对话.',
    'Reset Grid' => '重置表格',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => '拖动表格边缘来进行缩放',
    'Show all data' => '显示所有数据',
    'Show first page data' => '显示第一页数据',
    'Tab Delimited Text' => 'TAB键分割的文本',
    'Text' => '文本',
    'The CSV export file will be generated for download.' => '将会导出CSV文件以供下载',
    'The EXCEL export file will be generated for download.' => '将会导出EXCEL文件以供下载',
    'The HTML export file will be generated for download.' => '将会导出HTML文件以供下载',
    'The JSON export file will be generated for download.' => '将会导出JSON文件以供下载',
    'The PDF export file will be generated for download.' => '将会导出PDF文件以供下载',
    'The TEXT export file will be generated for download.' => '将会导出文本文件以供下载',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => '页面概要显示前三列的和以及最后一列的平均值',
    'The table header sticks to the top in this demo as you scroll' => '此示例中表头将在你滚动页面的时候固定在顶部',
    'There are {totalCount} records. Are you sure you want to display them all?' => '',
    'Update' => '更新',
    'View' => '查看',
    'Yii2 Grid Export (PDF)' => '由Yii2 Grid导出的PDF',
    'export' => '导出',
    'grid-export' => '导出表格',
    'krajee, grid, export, yii2-grid, pdf' => 'krajee, grid, export, yii2-grid, pdf',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Extensions',
];
