<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Tegevused',
    'Active' => 'Aktiivne',
    'Add Book' => 'Lisa raamat',
    'All' => 'Kõik',
    'Are you sure to delete this item?' => 'Oled kindel, et tahad selle kustutada?',
    'Book Listing' => '',
    'CSV' => '',
    'Clear selection' => 'Puhasta valik',
    'Collapse All' => '',
    'Collapse' => '',
    'Comma Separated Values' => 'Komaga eristatuc väärtused',
    'Delete' => 'Kustuta',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Palun ',
    'Download Selected' => 'Lae alla valitud',
    'Excel' => '',
    'Expand All' => '',
    'Expand' => '',
    'Export All Data' => 'Ekspordi kõik andmed',
    'Export Page Data' => 'Ekspordi lehe andmed',
    'Export' => 'Ekspordi',
    'ExportWorksheet' => '',
    'Generated' => 'Genereeritud',
    'Generating the export file. Please wait...' => 'Genereerin eksporditvat faili. Palun oota...',
    'Grid Export' => 'Tabeli eksportimine',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Inactive' => 'Mitteaktiivne',
    'Invalid editable index or model form name' => 'Vale muudetav indeks või mudel või vormi nimi',
    'Invalid or bad editable data' => 'Muudetavad andmed on valed või vigased',
    'JSON' => '',
    'JavaScript Object Notation' => '',
    'Library' => '',
    'Microsoft Excel 95+' => '',
    'No data found' => 'Andmeid ei leitud',
    'No valid editable model found' => 'Ei leidnud õiget muudetavat mudelit',
    'Ok to proceed?' => 'Kas jätkame? OK?',
    'PDF export generated by kartik-v/yii2-grid extension' => '',
    'PDF' => '',
    'Page' => 'Leht',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => '',
    'Reset Grid' => 'Lähtesta tabel',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Muuda veergusid nagu Excelis lohistades veeru ääri.',
    'Show all data' => 'Näita kõiki andmeid',
    'Show first page data' => 'Näita esimese lehe andmeid',
    'Tab Delimited Text' => '',
    'Text' => 'Tekst',
    'The CSV export file will be generated for download.' => 'Allalaadimiseks genereeritakse eksporditud andmetest CSV fail.',
    'The EXCEL export file will be generated for download.' => 'Allalaadimiseks genereeritakse eksporditud andmetest EXCELi fail.',
    'The HTML export file will be generated for download.' => 'Allalaadimiseks genereeritakse eksporditud andmetest HTML fail.',
    'The JSON export file will be generated for download.' => 'Allalaadimiseks genereeritakse eksporditud andmetest JSON fail.',
    'The PDF export file will be generated for download.' => 'Allalaadimiseks genereeritakse eksporditud andmetest PDF fail.',
    'The TEXT export file will be generated for download.' => 'Allalaadimiseks genereeritakse eksporditud andmetest TEXT fail.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => '',
    'The table header sticks to the top in this demo as you scroll' => '',
    'There are {totalCount} records. Are you sure you want to display them all?' => 'Kokku on {totalCount} ühikut. Oled sa kindel, et soovid kõiki neid kuvada?',
    'Update' => 'Uuenda',
    'View' => 'Vaata',
    'Yii2 Grid Export (PDF)' => '',
    'export' => 'ekspordi',
    'grid-export' => '',
    'krajee, grid, export, yii2-grid, pdf' => '',
    '© Krajee Yii2 Extensions' => '',
];
