<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Akce',
    'Active' => 'Aktivní',
    'Add Book' => 'Přidat knihu',
    'All' => 'Vše',
    'Are you sure to delete this {item}?' => 'Opravdu si přejete smazat tuto {item}?',
    'Book Listing' => 'Seznam knih',
    'CSV' => 'CSV',
    'Clear selection' => 'Zrušit výběr',
    'Collapse' => 'Sbalit',
    'Collapse All' => 'Sbalit vše',
    'Comma Separated Values' => 'Text oddělený středníkem',
    'Delete' => 'Smazat',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Povolte vyskakovací okna pro umožnění exportu.',
    'Download Selected' => 'Stáhnout vybrané',
    'Excel' => 'Excel',
    'Expand' => 'Rozbalit',
    'Expand All' => 'Rozbalit vše',
    'Export' => 'Export',
    'Export All Data' => 'Exportovat všechna data',
    'Export Page Data' => 'Exportovat data stránky',
    'ExportWorksheet' => 'Exportovat sešit',
    'Generated' => 'Vygenerováno',
    'Generating the export file. Please wait...' => 'Generování souboru. Počkejte prosím...',
    'Grid Export' => 'Export tabulky',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'HTML',
    'Inactive' => 'Neaktivní',
    'JSON' => 'JSON',
    'JavaScript Object Notation' => 'JSON',
    'Library' => 'Knihovna',
    'Microsoft Excel 95+' => 'Microsoft Excel 95+',
    'No data found' => 'Nenalezena žádná data',
    'Ok to proceed?' => 'Pokračovat?',
    'PDF' => 'PDF',
    'PDF export generated by kartik-v/yii2-grid extension' => 'PDF',
    'Page' => 'Strana',
    'Portable Document Format' => 'PDF',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Požadavek byl zpracován. Po uložení souboru můžete bezpečně zavřít toto okno.',
    'Reset Grid' => 'Obnovit tabulku',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Nastavte velikost sloupce tažením myší stejně jako v excelu.',
    'Show all data' => 'Zobrazit všechna data',
    'Show first page data' => 'Zobrazit data první stránky',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.' => '{totalCount, plural, one{Zobrazen} few{Zobrazeny} other{Zobrazeno}} <b>{totalCount, plural, one{{begin, number}} other{{begin, number}-{end, number}}}</b> z <b>{totalCount, number}</b> {totalCount, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'Tab Delimited Text' => 'Text oddělený tabelátory',
    'Text' => 'Text',
    'The CSV export file will be generated for download.' => 'CSV soubor bude vygenerován.',
    'The EXCEL export file will be generated for download.' => 'Excel soubor bude vygenerován.',
    'The HTML export file will be generated for download.' => 'HTML soubor bude vygenerován.',
    'The JSON export file will be generated for download.' => 'JSON soubor bude vygenerován.',
    'The PDF export file will be generated for download.' => 'PDF soubor bude vygenerován.',
    'The TEXT export file will be generated for download.' => 'Textový soubor bude vygenerován.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Shrnutí stránky zobrazuje součet pro prvé 3 číselné sloupce a průměr pro poslední sloupec.',
    'The table header sticks to the top in this demo as you scroll' => 'Záhlaví tabulky je během rolování nahoře ukotveno',
    'There are {totalCount} records. Are you sure you want to display them all?' => 'Bylo nalezeno {totalCount} záznamů. Opravdu si je přejete zobrazit všechny?',
    'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => 'Celkem <b>{count, number}</b> {count, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'Update' => 'Upravit',
    'View' => 'Zobrazit',
    'Yii2 Grid Export (PDF)' => 'Yii2 Grid Export (PDF)',
    'export' => 'export',
    'grid-export' => 'grid-export',
    'item' => 'záznamu',
    'items' => 'záznamů',
    'items-few' => 'záznamy',
    'items-many' => 'záznamů',
    'krajee, grid, export, yii2-grid, pdf' => 'krajee, grid, export, yii2-grid, pdf',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Extensions',
    'Failed to update editable data due to an unknown server error' => '',
    'Invalid editable index or model form name' => '',
    'Invalid or bad editable data' => '',
    'Krajee Solutions' => '',
    'Krajee Yii2 Grid Export Extension' => '',
    'No valid editable model found' => '',
    'items-acc' => '',
];
