<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Действия',
    'Active' => 'Вкл',
    'Add Book' => 'Добавить книгу',
    'All' => 'Все',
    'Are you sure to delete this {item}?' => 'Вы действительно хотите удалить данную {item}?',
    'Book Listing' => 'Содержимое книги',
    'CSV' => 'CSV',
    'Clear selection' => 'Убрать выделение',
    'Collapse' => 'Свернуть',
    'Collapse All' => 'Свернуть всё',
    'Comma Separated Values' => 'Данные, разделённые запятой',
    'Delete' => 'Удалить',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Чтобы скачать файл, отключите блокировку всплывающих окон в вашем браузере.',
    'Download Selected' => 'Загрузить выделенное',
    'Excel' => 'Excel',
    'Expand' => 'Развернуть',
    'Expand All' => 'Развернуть всё',
    'Export' => 'Экспорт',
    'Export All Data' => 'Экспорт всех данных',
    'Export Page Data' => 'Экспорт данных с текущей страницы',
    'ExportWorksheet' => 'ЭкспортPабочийЛист',
    'Failed to update editable data due to an unknown server error' => 'Произошла ошибка, не удалось обновить редактируемую информацию',
    'Generated' => 'Сгенерировано',
    'Generating the export file. Please wait...' => 'Файл для экспорта генерируется. Пожалуйста, ожидайте...',
    'Grid Export' => 'Экспорт таблицы',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'HTML',
    'Inactive' => 'Выкл',
    'Invalid editable index or model form name' => 'Неправильный индекс или имя формы',
    'Invalid or bad editable data' => 'Неправильные данные',
    'JSON' => 'JSON',
    'JavaScript Object Notation' => 'Формат данных JavaScript',
    'Library' => 'Библиотека',
    'Microsoft Excel 95+' => 'Microsoft Excel 95+',
    'No data found' => 'Данные не найдены',
    'No valid editable model found' => 'Данные не найдены',
    'Ok to proceed?' => 'Продолжить?',
    'PDF' => 'PDF',
    'PDF export generated by kartik-v/yii2-grid extension' => 'PDF сгенерирован расширением kartik-v/yii2-grid',
    'Page' => 'Страница',
    'Portable Document Format' => 'Mежплатформенный формат электронных документов (PDF)',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Сейчас начнётся загрузка файла. Пожалуйста, ожидайте...',
    'Reset Grid' => 'Сбросить таблицу',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Размер столбцов таблицы меняется так же, как таблицы - перетаскиванием края столбцов.',
    'Select...' => '',
    'Show all data' => 'Показать все записи',
    'Show first page data' => 'Показать первую страницу',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.' => 'Показаны <b>{begin, number}-{end, number}</b> из <b>{totalCount, number}</b> {count, plural, one{{item}} few{{items-few}} other{{items}}}.',
    'Tab Delimited Text' => 'Текст, разделённый пробелами (табами)',
    'Text' => 'Текст',
    'The CSV export file will be generated for download.' => 'Будет сгенерирован CSV файл для загрузки.',
    'The EXCEL export file will be generated for download.' => 'Будет сгенерирован EXCEL файл для загрузки.',
    'The HTML export file will be generated for download.' => 'Будет сгенерирован HTML файл для загрузки.',
    'The JSON export file will be generated for download.' => 'Будет сгенерирован JSON файл для загрузки.',
    'The PDF export file will be generated for download.' => 'Будет сгенерирован PDF файл для загрузки.',
    'The TEXT export file will be generated for download.' => 'Будет сгенерирован текстовый файл для загрузки.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Сводная страница отображает сумму 3 первых столбцов и среднее для последнего.',
    'The table header sticks to the top in this demo as you scroll' => 'В этой демо-версии заголовок таблицы прилипает к верху, когда вы скроллите',
    'There are {totalCount} records. Are you sure you want to display them all?' => 'Всего записей: {totalCount}. Хотите отобразить их все?',
    'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => 'Всего <b>{count, number}</b> {count, plural, one{{item}} few{{items-few}} many{{items}} other{{items}}}.',
    'Update' => 'Изменить',
    'View' => 'Просмотр',
    'Yii2 Grid Export (PDF)' => 'PDF экспорт таблицы Yii2',
    'export' => 'экспорт',
    'grid-export' => 'экспорт-таблицы',
    'item' => 'запись',
    'items' => 'записи',
    'items-few' => 'записи',
    'items-many' => 'записей',
    'krajee, grid, export, yii2-grid, pdf' => 'krajee, grid, сетка, export, экспорт, yii2-grid, pdf',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Расширения',
    '<small>Loading &hellip;</small>' => '',
    'Krajee Solutions' => '',
    'Krajee Yii2 Grid Export Extension' => '',
    'items-acc' => '',
];
