<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'View'=>'Visualizza',
    'Update'=>'Modifica',
    'Delete'=>'Elimina',
    'Are you sure to delete this item?'=>'Sei sicuro di volere eliminare questo elemento?',
    'Actions'=>'Opzioni',
    'HTML' => 'HTML',
    'CSV' => 'CSV',
    'Text' => 'Testo',
    'Excel' => 'Excel',
    'Save as HTML' => 'Salva come file HTML',
    'Save as CSV' => 'Salva come file CSV',
    'Save as Text' => 'Salva come file di testo',
    'Save as Excel' => 'Salva come file Excel',
    'Active' => 'Attivo',
    'Inactive' => 'Inattivo',
    'Export' => 'Esporta',
    'export' => '',
    'grid-export' => '',
    'The HTML export file will be generated for download.' => 'Sarà generato il file HTML da esportare.',
    'The CSV export file will be generated for download.' => 'Sarà generato il file CSV da esportare.',
    'The TEXT export file will be generated for download.' => 'Sarà generato il file di testo da esportare.',
    'The EXCEL export file will be generated for download.' => 'Sarà generato il file di Excel da esportare.',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Disabilita tutti i popup blockers per permettere un corretto utilizzo.',
    'No data found' => 'Nessun dato trovato',
    // Demo data
    'Library' => 'Libreria',
    'Book Listing' => 'Elenco Libri',
    'Add Book' => 'Aggiungi Libro',
    'Reset Grid' => 'Ricarica Grid',
    'Download Selected' => 'Scarica selezionati',
    'The table header sticks to the top in this demo as you scroll' => 'Blocca intestazione della tabella in alto durante lo scorrimento',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Il riepilogo pagina visualizza la somma per le prime colonne 3 e la media per l\'ultima.',
];
