<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All' => '',
    'Clear selection' => '',
    'Collapse' => '',
    'Collapse All' => '',
    'Comma Separated Values' => '',
    'Expand' => '',
    'Expand All' => '',
    'Export All Data' => '',
    'Failed to update editable data due to an unknown server error' => '',
    'Generated' => '',
    'Generating the export file. Please wait...' => '',
    'Grid Export' => '',
    'Hyper Text Markup Language' => '',
    'Invalid editable index or model form name' => '',
    'Invalid or bad editable data' => '',
    'JSON' => '',
    'JavaScript Object Notation' => '',
    'Microsoft Excel 95+' => '',
    'No valid editable model found' => '',
    'Ok to proceed?' => '',
    'PDF' => '',
    'PDF export generated by kartik-v/yii2-grid extension' => '',
    'Page' => '',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => '',
    'Show all data' => '',
    'Show first page data' => '',
    'Tab Delimited Text' => '',
    'The JSON export file will be generated for download.' => '',
    'The PDF export file will be generated for download.' => '',
    'There are {totalCount} records. Are you sure you want to display them all?' => '',
    'Yii2 Grid Export (PDF)' => '',
    'export' => '',
    'grid-export' => '',
    'krajee, grid, export, yii2-grid, pdf' => '',
    '© Krajee Yii2 Extensions' => '',
    'Actions' => 'Opzioni',
    'Active' => 'Attivo',
    'Add Book' => 'Aggiungi Libro',
    'Are you sure to delete this item?' => 'Sei sicuro di volere eliminare questo elemento?',
    'Book Listing' => 'Elenco Libri',
    'CSV' => 'CSV',
    'Delete' => 'Elimina',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Disabilita tutti i popup blockers per permettere un corretto utilizzo.',
    'Download Selected' => 'Scarica selezionati',
    'Excel' => 'Excel',
    'Export' => 'Esporta',
    'Export Page Data' => 'Esporta Pagina Dei Dati',
    'ExportWorksheet' => 'EksportérFoglioDiLavoro',
    'HTML' => 'HTML',
    'Inactive' => 'Inattivo',
    'Library' => 'Libreria',
    'No data found' => 'Nessun dato trovato',
    'Reset Grid' => 'Ricarica Grid',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Ridimensionare colonne della tabella come un foglio di calcolo trascinando i bordi delle colonne.',
    'Text' => 'Testo',
    'The CSV export file will be generated for download.' => 'Sarà generato il file CSV da esportare.',
    'The EXCEL export file will be generated for download.' => 'Sarà generato il file di Excel da esportare.',
    'The HTML export file will be generated for download.' => 'Sarà generato il file HTML da esportare.',
    'The TEXT export file will be generated for download.' => 'Sarà generato il file di testo da esportare.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Il riepilogo pagina visualizza la somma per le prime colonne 3 e la media per l\'ultima.',
    'The table header sticks to the top in this demo as you scroll' => 'Blocca intestazione della tabella in alto durante lo scorrimento',
    'Update' => 'Modifica',
    'View' => 'Visualizza',
];
