<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '© Krajee Yii2 Extensions' => '',
    'Actions' => 'Действия',
    'Active' => 'Вкл',
    'Add Book' => 'Добавить книгу',
    'All' => '',
    'Are you sure to delete this item?' => 'Вы действительно хотите удалить?',
    'Book Listing' => 'Содержимое книги',
    'Collapse' => '',
    'Collapse All' => '',
    'Comma Separated Values' => '',
    'CSV' => 'CSV',
    'Delete' => 'Удалить',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Чтобы скачать файл, отключите все блокировщики всплывающих окон в вашем браузере.',
    'Download Selected' => 'Загрузить выделенное',
    'Excel' => 'Excel',
    'Expand' => '',
    'Expand All' => '',
    'Export' => 'Экспорт',
    'export' => 'экспорт',
    'Export All Data' => '',
    'Export Page Data' => 'Экспорт Page данных',
    'ExportWorksheet' => 'ЭкспортPабочийлист',
    'Generated' => '',
    'Generating the export file. Please wait...' => '',
    'Grid Export' => '',
    'grid-export' => 'Сетка-экспорт',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => '',
    'Inactive' => 'Выкл',
    'JavaScript Object Notation' => '',
    'JSON' => '',
    'krajee, grid, export, yii2-grid, pdf' => '',
    'Library' => 'Библиотека',
    'Microsoft Excel 95+' => '',
    'No data found' => 'Данные не найдены',
    'Ok to proceed?' => '',
    'Page' => '',
    'PDF' => '',
    'PDF export generated by kartik-v/yii2-grid extension' => '',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => '',
    'Reset Grid' => 'Сбросить сетку',
    'Show all data' => '',
    'Show first page data' => '',
    'Tab Delimited Text' => '',
    'Text' => 'Text',
    'The CSV export file will be generated for download.' => 'Создать CSV файл для загрузки.',
    'The EXCEL export file will be generated for download.' => 'Создать EXCEL файл для загрузки.',
    'The HTML export file will be generated for download.' => 'Создать HTML файл для загрузки.',
    'The JSON export file will be generated for download.' => '',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Сводная страница отобрает сумму 3 первых столбцов и среднее для последнего.',
    'The PDF export file will be generated for download.' => '',
    'The table header sticks to the top in this demo as you scroll' => 'В этой демо заголовок таблицы прилипает к верху, пока вы скроллируете',
    'The TEXT export file will be generated for download.' => 'Создать TEXT файл для загрузки.',
    'Update' => 'Обновить',
    'View' => 'Смотреть',
    'Yii2 Grid Export (PDF)' => '',
];
