<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'HTML' => 'HTML',
    'CSV' => 'CSV',
    'Text' => 'Texto',
    'Excel' => 'Excel',
    'Save as HTML' => 'Salvar como HTML',
    'Save as CSV' => 'Salvar como CSV',
    'Save as Text' => 'Salvar como Texto',
    'Save as Excel' => 'Salvar como Excel',
    'Active' => 'Ativo',
    'Inactive' => 'Inativo',
    'Actions' => 'Ações',
    'Export' => 'Exportar',
    'export' => 'exportar',
    'grid-export' => 'grade-exportacao',
    'The HTML export file will be generated for download.' => 'O arquivo de exportação HTML será gerada para download.',
    'The CSV export file will be generated for download.' => 'O arquivo de exportação CSV será gerada para download.',
    'The TEXT export file will be generated for download.' => 'O arquivo de exportação TEXTO será gerada para download.',
    'The EXCEL export file will be generated for download.' => 'O arquivo de exportação EXCEL será gerada para download.',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Desative todos os bloqueadores de popup no seu navegador para garantir o download.',
    'No data found' => 'Nenhum arquivo encontrado.',
];
