<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Failed to update editable data due to an unknown server error' => '',
    'Actions' => 'Akcia',
    'Active' => 'Aktívne',
    'Add Book' => 'Pridať knihu',
    'All' => 'Všetko',
    'Are you sure to delete this item?' => 'Naozaj si prajete zmazať túto položku?',
    'Book Listing' => 'Zoznam kníh',
    'CSV' => 'CSV',
    'Clear selection' => 'Zrušiť výber',
    'Collapse' => 'Zbaliť',
    'Collapse All' => 'Zbaliť všetko',
    'Comma Separated Values' => 'Text oddelený čiarkou',
    'Delete' => 'Zmazať',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Povoľte vyskakovacie okná pre umožnenie exportu.',
    'Download Selected' => 'Stiahnuť vybrané',
    'Excel' => 'Excel',
    'Expand' => 'Rozbaliť',
    'Expand All' => 'Rozbaliť všetko',
    'Export' => 'Export',
    'Export All Data' => 'Exportovať všetky dáta',
    'Export Page Data' => 'Exportovať dáta stránky',
    'ExportWorksheet' => 'Exportovať zošit',
    'Generated' => 'Vygenerované',
    'Generating the export file. Please wait...' => 'Generovanie súboru. Čakajte prosím...',
    'Grid Export' => 'Export tabuľky',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'HTML',
    'Inactive' => 'Neaktívne',
    'Invalid editable index or model form name' => 'Neplatný editovateľný index alebo názov formulára',
    'Invalid or bad editable data' => 'Neplatné alebo zle editované dáta',
    'JSON' => 'JSON',
    'JavaScript Object Notation' => 'JSON',
    'Library' => 'Knižnica',
    'Microsoft Excel 95+' => 'Microsoft Excel 95+',
    'No data found' => 'Nenájdené žiadne dáta',
    'No valid editable model found' => 'Nenájdený platný editovateľný model',
    'Ok to proceed?' => 'Pokračovat?',
    'PDF' => 'PDF',
    'PDF export generated by kartik-v/yii2-grid extension' => 'PDF export generovaný rozšírením kartik-v/yii2-grid',
    'Page' => 'Strana',
    'Portable Document Format' => 'PDF',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Požiadavka bola spracovaná. Po uložení súboru môžete bezpečne zatvoriť toto okno.',
    'Reset Grid' => 'Obnoviť tabuľku',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Nastavte veľkosť stĺpca ťahaním myšky rovnako ako v excely.',
    'Show all data' => 'Zobraziť všetky dáta',
    'Show first page data' => 'Zobraziť dáta prvej stránky',
    'Tab Delimited Text' => 'Text oddelený tabulátormi',
    'Text' => 'Text',
    'The CSV export file will be generated for download.' => 'CSV súbor bude vygenerovaný na stiahnutie.',
    'The EXCEL export file will be generated for download.' => 'Excel súbor bude vygenerovaný na stiahnutie.',
    'The HTML export file will be generated for download.' => 'HTML súbor bude vygenerovaný na stiahnutie.',
    'The JSON export file will be generated for download.' => 'JSON súbor bude vygenerovaný na stiahnutie.',
    'The PDF export file will be generated for download.' => 'PDF súbor bude vygenerovaný na stiahnutie.',
    'The TEXT export file will be generated for download.' => 'Textový súbor bude vygenerovaný na stiahnutie.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Zhrnutie stránky zobrazuje súčet pre prvé 3 číselné stĺpce a priemer pre posledný stĺpec.',
    'The table header sticks to the top in this demo as you scroll' => 'Záhlavie tabuľky je počas skrolovania navrchu ukotvený',
    'There are {totalCount} records. Are you sure you want to display them all?' => 'Bolo nájdených {totalCount} záznamov. Naozaj si ich prajete zobraziť všetky?',
    'Update' => 'Upraviť',
    'View' => 'Zobraziť',
    'Yii2 Grid Export (PDF)' => 'Yii2 Grid Export (PDF)',
    'export' => 'export',
    'grid-export' => 'grid-export',
    'krajee, grid, export, yii2-grid, pdf' => 'krajee, grid, export, yii2-grid, pdf',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Extensions',
];
