<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Clear selection' => '',
    'Collapse' => '',
    'Collapse All' => '',
    'Expand' => '',
    'Expand All' => '',
    'Actions' => 'Acciones',
    'Active' => 'Activo',
    'Add Book' => 'Agregar Libro',
    'All' => 'Todo',
    'Are you sure to delete this item?' => '¿Esta seguro de eliminar este registro?',
    'Book Listing' => 'Listando libros',
    'CSV' => 'CSV',
    'Comma Separated Values' => 'Valores separados por comas',
    'Delete' => 'Eliminar',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Deshabilite cualquier bloqueador de ventanas emergentes, para una descarga adecuada',
    'Download Selected' => 'Descargar Seleccionados',
    'Excel' => 'Excel',
    'Export' => 'Exportar',
    'Export All Data' => 'Exportar Todos los Datos',
    'Export Page Data' => 'Exportar los Datos de esta Página',
    'ExportWorksheet' => 'Exportar Hoja de Trabajo',
    'Generated' => 'Generado',
    'Generating the export file. Please wait...' => 'Generando archivo de exportación. Por favor espere.',
    'Grid Export' => 'Exportar la Cuadrícula',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'Hyper Text Markup Language',
    'Inactive' => 'Inactivo',
    'JSON' => 'JSON',
    'JavaScript Object Notation' => 'JavaScript Object Notation',
    'Library' => 'Librería',
    'Microsoft Excel 95+' => 'Microsoft Excel 95+',
    'No data found' => 'Datos no encontrados',
    'Ok to proceed?' => 'OK para proceder',
    'PDF' => 'PDF',
    'PDF export generated by kartik-v/yii2-grid extension' => 'Exportación a PDF por kartik-v/yii2-grid extension',
    'Page' => 'Página',
    'Portable Document Format' => 'Portable Document Format',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => '¡Solicitud Enviada! Usted puede cerrar esta ventana luego de guardar su archivo descargado',
    'Reset Grid' => 'Reiniciar Cuadrícula',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Cambiar el tamaño de las columnas de tabla como una hoja de cálculo arrastrando los bordes de las columnas.',
    'Show all data' => 'Mostrar todos los datos',
    'Show first page data' => 'Mostrar primera página de datos',
    'Tab Delimited Text' => 'Texto Delimitado por Tabulaciones',
    'Text' => 'Texto',
    'The CSV export file will be generated for download.' => 'El archivo CSV será generado para descargar.',
    'The EXCEL export file will be generated for download.' => 'El archivo EXCEL será generado para descargar.',
    'The HTML export file will be generated for download.' => 'El archivo HTML será generado para descargar.',
    'The JSON export file will be generated for download.' => 'El archivo JSON será generado para descargar.',
    'The PDF export file will be generated for download.' => 'El archivo PDF será generado para descargar.',
    'The TEXT export file will be generated for download.' => 'El archivo de TEXTO será generado para descargar.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'El resumen de la página mostrará la SUMA de los montos de las 3 primeras columnas y el PROMEDIO para el resto',
    'The table header sticks to the top in this demo as you scroll' => 'El encabezado de la tabla se mantendrá fijo en este demo mientras usted se desplaza',
    'Update' => 'Actualizar',
    'View' => 'Ver',
    'Yii2 Grid Export (PDF)' => 'Yii2 Exportar cuadrícula (PDF)',
    'export' => 'exportar',
    'grid-export' => 'exportar-cuadrícula',
    'krajee, grid, export, yii2-grid, pdf' => 'krajee, cuadrícula, exportar, yii2-grid, pdf',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Extensions',
];
