<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'ดำเนินการ',
    'All' => 'ทั้งหมด',
    'Are you sure to delete this {item}?' => 'คุณมั่นใจว่าต้องการลบข้อมูลนี้ {item}',
    'Clear selection' => 'ล้างข้อมูลที่เลือก',
    'Collapse' => 'ย่อ',
    'Collapse All' => 'ย่อทั้งหมด',
    'Delete' => 'ลบ',
    'Download Selected' => 'ดาวน์โหลดข้อมูลที่เลือก',
    'Expand' => 'ขยาย',
    'Expand All' => 'ขยายทั้งหมด',
    'Export' => 'ส่งออก',
    'Export All Data' => 'ส่งออกข้อมูลทั้งหมด',
    'Export Page Data' => 'ส่งออกข้อมูลเฉพาะหน้า',
    'Generated' => 'สร้างสำเร็จ',
    'Generating the export file. Please wait...' => 'กำลังสร้างไฟล์ส่งออก กรุณารอ...',
    'No data found' => 'ไม่พบข้อมูล',
    'Page' => 'หน้า',
    'Select...' => '',
    'Show all data' => 'แสดงข้อมูลทั้งหมด',
    'Show first page data' => 'แสดงข้อมูลหน้าแรก',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.' => 'แสดง <b>{begin, number} ถึง {end, number}</b> จาก <b>{totalCount, number}</b> ผลลัพธ์',
    'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => 'ทั้งหมด <b>{count, number}</b> ผลลัพธ์',
    'Update' => 'ปรับปรุง',
    'View' => 'ดู',
    'export' => 'ส่งออก',
    'items-few' => 'items',
    'items-many' => 'items',
    '<small>Loading &hellip;</small>' => '',
    'Active' => '',
    'Add Book' => '',
    'Book Listing' => '',
    'CSV' => '',
    'Comma Separated Values' => '',
    'Disable any popup blockers in your browser to ensure proper download.' => '',
    'Excel' => '',
    'ExportWorksheet' => '',
    'Failed to update editable data due to an unknown server error' => '',
    'Grid Export' => '',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Inactive' => '',
    'Invalid editable index or model form name' => '',
    'Invalid or bad editable data' => '',
    'JSON' => '',
    'JavaScript Object Notation' => '',
    'Krajee Solutions' => '',
    'Krajee Yii2 Grid Export Extension' => '',
    'Library' => '',
    'Microsoft Excel 95+' => '',
    'No valid editable model found' => '',
    'Ok to proceed?' => '',
    'PDF' => '',
    'PDF export generated by kartik-v/yii2-grid extension' => '',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => '',
    'Reset Grid' => '',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => '',
    'Tab Delimited Text' => '',
    'Text' => '',
    'The CSV export file will be generated for download.' => '',
    'The EXCEL export file will be generated for download.' => '',
    'The HTML export file will be generated for download.' => '',
    'The JSON export file will be generated for download.' => '',
    'The PDF export file will be generated for download.' => '',
    'The TEXT export file will be generated for download.' => '',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => '',
    'The table header sticks to the top in this demo as you scroll' => '',
    'There are {totalCount} records. Are you sure you want to display them all?' => '',
    'Yii2 Grid Export (PDF)' => '',
    'grid-export' => '',
    'item' => '',
    'items' => '',
    'items-acc' => '',
    'krajee, grid, export, yii2-grid, pdf' => '',
    '© Krajee Yii2 Extensions' => '',
];
