<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'عملیات',
    'Active' => 'فعال',
    'Add Book' => 'افزودن کتاب',
    'All' => 'همه موارد',
    'Are you sure to delete this {item}?' => 'آیا از حذف این {item} اطمینان دارید؟',
    'Book Listing' => 'لیست کتابها',
    'CSV' => 'CSV',
    'Clear selection' => 'پاک کردن انتخاب ها',
    'Collapse' => 'جمع کردن',
    'Collapse All' => 'جمع کردن همه موارد',
    'Comma Separated Values' => 'مقادیر جدا شده به وسیله کاما',
    'Delete' => 'حذف',
    'Disable any popup blockers in your browser to ensure proper download.' => 'برای اطمینان از صحت دانلود، مسدود کننده پاپ آپ مرورگر خود را غیر فعال کنید.',
    'Download Selected' => 'دانلود منتخب ها',
    'Excel' => 'اکسل',
    'Expand' => 'گسترش',
    'Expand All' => 'گسترش همه موارد',
    'Export' => 'خروجی',
    'Export All Data' => 'خروجی همه  داده ها',
    'Export Page Data' => 'خروجی داده های صفحه',
    'ExportWorksheet' => 'خروجی از صفحه',
    'Failed to update editable data due to an unknown server error' => 'به دلیل یک خطای سرور ناشناخته، به روز رسانی فیلد قابل ویرایش انجام نشد',
    'Generated' => 'تولید شد',
    'Generating the export file. Please wait...' => 'در حال تولید فایل خروجی. لطفا منتظر باشید',
    'Grid Export' => 'خروجی گرید',
    'Hyper Text Markup Language' => 'زبان نشانه گذاری اَبَر متن',
    'Inactive' => 'غیرفعال',
    'Invalid editable index or model form name' => 'شاخص یا مدل نام فرم برای فیلد قابل ویرایش اشتباه است',
    'Invalid or bad editable data' => 'داده فیلد قابل ویرایش اشتباه یا به صورت بد می‌باشد',
    'JavaScript Object Notation' => 'زبان نشانه‌گذاری جاوا اسکریپت',
    'Library' => 'کتابخانه',
    'No data found' => 'داده ای پیدا نشد',
    'No valid editable model found' => 'مدل معتبر برای فیلد قابل ویرایش یافت نشد.',
    'Ok to proceed?' => 'تایید برای پردازش؟',
    'Page' => 'صفحه',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'درخواست ارسال شد! شما با خیال راحت ممکن می‌توانید این صفحه را پس از ذخیره فایل های دانلود شده خود ببندید.',
    'Reset Grid' => 'بازنشانی گرید',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'ستون های جدول را مثل یک صفحه گسترده با کشیدن لبه های ستون تغییر دهید.',
    'Show all data' => 'نمایش تمام اطلاعات',
    'Show first page data' => 'نمایش اطلاعات صفحه اول',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.' => 'نمایش <b>{begin, number} تا {end, number}</b> مورد از کل <b>{totalCount, number}</b> {totalCount, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'Tab Delimited Text' => 'متن جدا شده توسط Tab',
    'Text' => 'متن',
    'The CSV export file will be generated for download.' => 'فایل CSV خروجی برای دانلود ایجاد خواهد شد.',
    'The EXCEL export file will be generated for download.' => 'فایل EXCEL خروجی برای دانلود ایجاد خواهد شد.',
    'The HTML export file will be generated for download.' => 'فایل HTML خروجی برای دانلود ایجاد خواهد شد.',
    'The JSON export file will be generated for download.' => 'فایل JSON خروجی برای دانلود ایجاد خواهد شد.',
    'The PDF export file will be generated for download.' => 'فایل PDF خروجی برای دانلود ایجاد خواهد شد.',
    'The TEXT export file will be generated for download.' => 'فایل TEXT خروجی برای دانلود ایجاد خواهد شد.',
    'The table header sticks to the top in this demo as you scroll' => 'عنوان جدول بعد از سکرول به بالا میچسبد در این نسخه آزمایشی',
    'There are {totalCount} records. Are you sure you want to display them all?' => '{totalCount} رکورد وجود دارد. آیا مطمئن هستید که می خواهید همه آنها را نمایش دهید؟',
    'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => 'مجموع <b>{count, number}</b> {count, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'Update' => 'بروزرسانی',
    'View' => 'نما',
    'export' => 'خروجی',
    'grid-export' => 'خروجی گرید',
    'item' => 'مورد',
    'items' => 'مورد',
    'items-few' => 'موارد کم',
    'items-many' => 'موارد زیاد',
    'HTML' => '',
    'JSON' => '',
    'Krajee Solutions' => '',
    'Krajee Yii2 Grid Export Extension' => '',
    'Microsoft Excel 95+' => '',
    'PDF' => '',
    'PDF export generated by kartik-v/yii2-grid extension' => '',
    'Portable Document Format' => '',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => '',
    'Yii2 Grid Export (PDF)' => '',
    'items-acc' => '',
    'krajee, grid, export, yii2-grid, pdf' => '',
    '© Krajee Yii2 Extensions' => '',
];
