<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.' => 'عرض <b>{begin, number}-{end, number}</b> من أصل <b>{totalCount, number}</b> {totalCount, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => 'مجموع <b>{count, number}</b> {count, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'item' => 'مُدخل',
    'items' => 'مُدخلات',
    'items-few' => 'مُدخلات',
    'items-many' => 'مُدخل',
    '<small>Loading &hellip;</small>' => '',
    'Actions' => 'احداث',
    'Active' => 'فعّال',
    'Add Book' => 'إضافة كتاب',
    'All' => 'الجميع',
    'Are you sure to delete this {item}?' => 'هل انت متأكد من حذف هذا {item}؟',
    'Book Listing' => 'كتب مسموعة',
    'CSV' => '',
    'Clear selection' => 'تنظيف القسم',
    'Collapse' => 'إغلاق',
    'Collapse All' => 'إغلاق الجميع',
    'Comma Separated Values' => 'قيم مفصولة بفواصل',
    'Delete' => 'حذف',
    'Disable any popup blockers in your browser to ensure proper download.' => 'قم يإقاف مانع الاعلانات في المتصفح لتأكيد التحميل.',
    'Download Selected' => 'تحميل المحدد',
    'Excel' => '',
    'Expand' => 'توسيع',
    'Expand All' => 'توسيع الكل',
    'Export' => 'تصدير',
    'Export All Data' => 'تصدير جميع البيانات',
    'Export Page Data' => 'تصدير بيانات الصفحة',
    'ExportWorksheet' => 'تصدير ورقة العمل',
    'Failed to update editable data due to an unknown server error' => 'فشل تحديث البيانات القابلة للتحرير بسبب خطأ غير معروف في الخادم',
    'Generated' => 'تم التوليد',
    'Generating the export file. Please wait...' => 'جارِ توليد الملف. الرجاء الانتظار...',
    'Grid Export' => 'تصدير الجدول',
    'HTML' => '',
    'Hyper Text Markup Language' => 'لغة توصيف النص الفائق',
    'Inactive' => 'غبر مفعّل',
    'Invalid editable index or model form name' => 'البيانات القابلة للتحرير او اسم النموذج غير صالحين',
    'Invalid or bad editable data' => 'البيانات القابلة للتحرير غير صالحة',
    'JSON' => '',
    'JavaScript Object Notation' => '',
    'Krajee Solutions' => 'حلول Krajee',
    'Krajee Yii2 Grid Export Extension' => 'اضافة استخراج الجدول من Krajee Yii2',
    'Library' => 'مكتبة',
    'Microsoft Excel 95+' => '',
    'No data found' => 'لم يتم ايجاد بيانات',
    'No valid editable model found' => 'لم يتم العثور على النموذج القابل للتحرير',
    'Ok to proceed?' => 'موافق على المعالجة؟',
    'PDF' => '',
    'PDF export generated by kartik-v/yii2-grid extension' => 'تصدير PDF تم إنشاؤه بواسطة kartik-v / yii2-grid',
    'Page' => 'صفحة',
    'Portable Document Format' => 'تنسيق نصي محمول',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'تم تقديم الطلب! يمكنك إغلاق مربع الحوار هذا بأمان بعد حفظ الملف الذي تم تنزيله.',
    'Reset Grid' => 'إعادة تعيين الجدول',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'قم بتغيير حجم أعمدة الجدول تمامًا مثل جدول البيانات عن طريق سحب حواف الأعمدة.',
    'Select...' => 'تحديد...',
    'Show all data' => 'إظهار جميع البيانات',
    'Show first page data' => 'إظهار بيانات الصفحة الاولى',
    'Tab Delimited Text' => 'نص محدد بعلامات جدولة',
    'Text' => 'نص',
    'The CSV export file will be generated for download.' => 'سيتم إنشاء ملف تصدير CSV للتنزيل.',
    'The EXCEL export file will be generated for download.' => 'سيتم إنشاء ملف تصدير EXCEL للتنزيل.',
    'The HTML export file will be generated for download.' => 'سيتم إنشاء ملف تصدير HTML للتنزيل.',
    'The JSON export file will be generated for download.' => 'سيتم إنشاء ملف تصدير JSON للتنزيل.',
    'The PDF export file will be generated for download.' => 'سيتم إنشاء ملف تصدير PDF للتنزيل.',
    'The TEXT export file will be generated for download.' => 'سيتم إنشاء ملف تصدير TEXT للتنزيل.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'يعرض ملخص الصفحة مجموع الأعمدة الثلاثة الأولى و المتوسط الحسابي للأخيرة.',
    'The table header sticks to the top in this demo as you scroll' => 'يلتصق رأس الجدول بالأعلى في هذا العرض التوضيحي أثناء التمرير',
    'There are {totalCount} records. Are you sure you want to display them all?' => 'هناك {totalCount} من السجلات. هل أنت متأكد أنك تريد عرضها جميعًا؟',
    'Update' => 'تحديث',
    'View' => 'عرض',
    'Yii2 Grid Export (PDF)' => '',
    'export' => 'تصدير',
    'grid-export' => 'تصدير الجدول',
    'items-acc' => '',
    'krajee, grid, export, yii2-grid, pdf' => '',
    '© Krajee Yii2 Extensions' => 'إضافات © Krajee Yii2',
];
