<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'ક્રિયાઓ',
    'Active' => 'સકિય',
    'Add Book' => 'બુક ઉમેરો',
    'All' => 'બધા',
    'Are you sure to delete this {item}?' => 'તમે આ {item} કાઢી નાખવા માંગો છો તમને ખાતરી છે?',
    'Book Listing' => 'પુસ્તક ની યાદી',
    'Clear selection' => 'સ્પષ્ટ પસંદગી',
    'Collapse' => 'કૉલેપ્સ',
    'Collapse All' => 'બધા કૉલેપ્સ કરો',
    'Comma Separated Values' => 'અલ્પવિરામથી અલગ પડેલ કિંમતો',
    'Delete' => 'દૂર કરો',
    'Disable any popup blockers in your browser to ensure proper download.' => 'યોગ્ય ડાઉનલોડ તેની ખાતરી કરવા માટે તમારા બ્રાઉઝરમાં કોઈપણ પોપઅપ બ્લોકર નિષ્ક્રિય કરો.',
    'Download Selected' => 'પસંદ કરેલ ડાઉનલોડ કરો',
    'Expand' => 'વિસ્તૃત કરો',
    'Expand All' => 'તમામ વિસ્તૃત કરો',
    'Export' => 'એક્સપૉર્ટ',
    'Export All Data' => 'તમામ ડેટા એક્સપૉર્ટ કરો',
    'Export Page Data' => 'પેજની માહિતી એક્સપૉર્ટ કરો',
    'ExportWorksheet' => 'એક્સપૉર્ટ વર્કશીટ',
    'Failed to update editable data due to an unknown server error' => 'અજ્ઞાત સર્વર ભૂલને કારણે ફેરફાર કરી શકાય તેવી માહિતી અપડેટ કરવામાં નિષ્ફળ',
    'Generated' => 'બનાવેલ',
    'Generating the export file. Please wait...' => 'ફાઇલ બની રહી છે. મહેરબાની કરી રાહ જુવો...',
    'Grid Export' => 'ગ્રીડ એક્સપૉર્ટ',
    'Hyper Text Markup Language' => 'હાઇપરટેક્સ્ટ માર્કઅપ લેંગ્વેજ',
    'Inactive' => 'નિષ્ક્રિય',
    'Invalid editable index or model form name' => 'ઇન્ડેક્સ અથવા મોડેલ ફોર્મ નામ મા અમાન્ય ફેરફાર',
    'Invalid or bad editable data' => 'અમાન્ય અથવા ખરાબ ફેરફાર કરી શકાય તેવી માહિતી',
    'JavaScript Object Notation' => 'જાવાસ્ક્રિપ્ટ ઑબ્જેક્ટ નોટેશન',
    'Library' => 'પુસ્તકાલય',
    'Microsoft Excel 95+' => 'માઈક્રોસોફ્ટ એક્સેલ 95+',
    'No data found' => 'કોઈ માહિતી મળી નથી',
    'No valid editable model found' => 'કોઈ માન્ય ફેરફાર કરી શકાય તેવી મોડલ મળી નથી',
    'Ok to proceed?' => 'આગળ વધવા માટે ઓકે?',
    'PDF export generated by kartik-v/yii2-grid extension' => 'પીડીએફ નિકાસ kartik-v/yii2-grid extension દ્વારા બનાવવામા આવી',
    'Page' => 'પેજ',
    'Portable Document Format' => 'પોર્ટેબલ ડોક્યુમેન્ટ ફોર્મેટ',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'તમારી વિનંતી સબમિટ કરી! તમે સુરક્ષિત રીતે ફાઇલ ડાઉનલોડ કયાઁ પછી આ સંવાદ બંધ કરી શકો છો.',
    'Reset Grid' => 'ગ્રીડ રીસેટ કરો',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'કોલમની કોરને ખેંચીને કૉલમ્સનુ માપ બદલો.',
    'Select...' => '',
    'Show all data' => 'બધી માહિતી બતાવો',
    'Show first page data' => 'પહેલા પેજની માહિતી બતાવો',
    'Tab Delimited Text' => 'ટેબ સીમાંકિત લખાણ',
    'Text' => 'ટેક્સ્ટ',
    'The CSV export file will be generated for download.' => 'ડાઉનલોડ કરવા માટે CSV એક્સપૉર્ટ ફાઈલ બનાવવામાં આવી છે.',
    'The EXCEL export file will be generated for download.' => 'ડાઉનલોડ કરવા માટે EXCEL એક્સપૉર્ટ ફાઈલ બનાવવામાં આવી છે.',
    'The HTML export file will be generated for download.' => 'ડાઉનલોડ કરવા માટે HTML એક્સપૉર્ટ ફાઈલ બનાવવામાં આવી છે.',
    'The JSON export file will be generated for download.' => 'ડાઉનલોડ કરવા માટે JSON એક્સપૉર્ટ ફાઈલ બનાવવામાં આવી છે.',
    'The PDF export file will be generated for download.' => 'ડાઉનલોડ કરવા માટે PDF એક્સપૉર્ટ ફાઈલ બનાવવામાં આવી છે.',
    'The TEXT export file will be generated for download.' => 'ડાઉનલોડ કરવા માટે TEXT એક્સપૉર્ટ ફાઈલ બનાવવામાં આવી છે.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'પેજ સારાંશ પ્રથમ 3 રકમ કૉલમ અને  છેલ્લા માટે સરેરાશ દર્શાવે છે.',
    'The table header sticks to the top in this demo as you scroll' => 'આ ઉદાહરણમાં જેમ તમે સ્ક્રોલ કરશો તેમ ટેબલ હેડર ઉપર ચોટેલ રેહશે',
    'There are {totalCount} records. Are you sure you want to display them all?' => 'ત્યાં {totalCount} રેકોર્ડ છે. તમે તેમને બધા પ્રદર્શિત કરવા માંગો છો શું તમને ખાતરી છે?',
    'Update' => 'અપડેટ',
    'View' => 'જુઓ',
    'Yii2 Grid Export (PDF)' => 'Yii2 ગ્રીડ એક્સપૉર્ટ (PDF)',
    'export' => 'એક્સપૉર્ટ',
    'grid-export' => 'ગ્રીડ-એક્સપૉર્ટ',
    'item' => 'રેકોર્ડ',
    'items' => 'રેકોર્ડ',
    'krajee, grid, export, yii2-grid, pdf' => 'krajee, ગ્રીડ, એક્સપૉર્ટ, yii2-grid, pdf',
    '<small>Loading &hellip;</small>' => '',
    'CSV' => '',
    'Excel' => '',
    'HTML' => '',
    'JSON' => '',
    'Krajee Solutions' => '',
    'Krajee Yii2 Grid Export Extension' => '',
    'PDF' => '',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.' => '',
    'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => '',
    'items-acc' => '',
    'items-few' => '',
    'items-many' => '',
    '© Krajee Yii2 Extensions' => '',
];
