<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Eylemler',
    'Active' => 'Etkin',
    'Add Book' => 'Kitap Ekle',
    'All' => 'Tümü',
    'Are you sure to delete this item?' => 'Bu öğeyi silmek istediğinize emin misiniz?',
    'Book Listing' => 'Kitap Listesi',
    'CSV' => 'CSV',
    'Clear selection' => 'Seçimi temizle',
    'Collapse All' => 'Tümünü Daralt',
    'Collapse' => 'Daralt',
    'Comma Separated Values' => 'Virgülle Ayrılmış Değerler (CSV)',
    'Delete' => 'Sil',
    'Disable any popup blockers in your browser to ensure proper download.' => 'İndirmeyi sağlamak için tarayıcınızda açılır pencere engelleyiciyi devre dışı bırakın.',
    'Download Selected' => 'Seçilenleri İndir',
    'Excel' => 'Excel',
    'Expand All' => 'Tümünü Genişlet',
    'Expand' => 'Genişlet',
    'Export All Data' => 'Tüm Verileri Dışa Aktar',
    'Export Page Data' => 'Sayfa Bilgisini Dışa Aktar',
    'Export' => 'Dışa Aktar',
    'ExportWorksheet' => 'Çalışma Sayfasına Aktar',
    'Generated' => 'Oluşturudu',
    'Generating the export file. Please wait...' => 'Dışa Aktarma dosyası oluşturuluyor. Lütfen bekleyin...',
    'Grid Export' => 'Izgara Dışa Aktar',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'Hyper Text Markup Language',
    'Inactive' => 'Etkin değil',
    'Invalid editable index or model form name' => '',
    'Invalid or bad editable data' => '',
    'JSON' => 'JSON',
    'JavaScript Object Notation' => 'JavaScript Object Notation',
    'Library' => 'Kütüphane',
    'Microsoft Excel 95+' => 'Microsoft Excel 95 +',
    'No data found' => 'Hiç veri bulunamadı',
    'No valid editable model found' => '',
    'Ok to proceed?' => 'Devam edilsin mi?',
    'PDF export generated by kartik-v/yii2-grid extension' => 'Kartik-v / yii2-grid uzantısı tarafından oluşturulan PDF çıktısı',
    'PDF' => 'PDF',
    'Page' => 'Sayfa',
    'Portable Document Format' => 'Taşınabilir Belge Biçimi',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'İstek gönderildi! İndirilen dosyayı kaydettikten sonra güvenle bu iletişim kutusunu kapatabilir.',
    'Reset Grid' => 'Izgarayı Sıfırla',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Sadece kolon kenarlarını sürükleyerek bir tablo gibi sütunları yeniden boyutlandırınız.',
    'Show all data' => 'Tüm verileri göster',
    'Show first page data' => 'İlk sayfa verisini göster',
    'Tab Delimited Text' => 'Tab ile ayrılmış metin',
    'Text' => 'Metin',
    'The CSV export file will be generated for download.' => 'CSV Dışa Aktarma dosyası indirmek için oluşturulacaktır.',
    'The EXCEL export file will be generated for download.' => 'EXCEL Dışa Aktarma dosyası indirmek için oluşturulacaktır.',
    'The HTML export file will be generated for download.' => 'HTML Dışa Aktarma dosyası indirmek için oluşturulacaktır.',
    'The JSON export file will be generated for download.' => 'JSON Dışa Aktarma dosyası indirmek için oluşturulacaktır.',
    'The PDF export file will be generated for download.' => 'PDF dışa aktarma dosyası indirmek için oluşturulacaktır.',
    'The TEXT export file will be generated for download.' => 'METİN Dışa Aktarma dosyası indirmek için oluşturulacaktır.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Sayfa özeti ilk 3 miktarı sütunun toplamını ve son sütünun ortalamasını görüntüler.',
    'The table header sticks to the top in this demo as you scroll' => 'Bu demoda tablo başlıkları sayfa kaydırıldığında yukarı yapışır.',
    'There are {totalCount} records. Are you sure you want to display them all?' => '',
    'Update' => 'Güncelle',
    'View' => 'Görünüm',
    'Yii2 Grid Export (PDF)' => 'Yii2 Izgara Dışarı Aktarımı (PDF)',
    'export' => 'dışa aktarım',
    'grid-export' => 'Izgara Dışa Aktar',
    'krajee, grid, export, yii2-grid, pdf' => 'Krajee, ızgara, ihracat, yii2-ızgara, pdf',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Uzantıları',
];
