<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => '',
    'Active' => '',
    'Add Book' => 'Ajouter un livre',
    'All' => 'Tous',
    'Are you sure to delete this item?' => 'Êtes vous sur de supprimer cet article ?',
    'Book Listing' => 'Liste de livres',
    'CSV' => '',
    'Clear selection' => '',
    'Collapse All' => '',
    'Collapse' => '',
    'Comma Separated Values' => 'Valeur séparées par des virgules',
    'Delete' => 'Supprimer',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Désactiver tous les bloqueurs de publicité pour s\'assurer un téléchargement correct',
    'Download Selected' => 'Télécharger les articles sélectionnés',
    'Excel' => '',
    'Expand All' => '',
    'Expand' => '',
    'Export All Data' => 'Exporter toute les données',
    'Export Page Data' => 'Exporter les données de la page',
    'Export' => 'Exporter',
    'ExportWorksheet' => '',
    'Generated' => 'Généré',
    'Generating the export file. Please wait...' => 'Génération du fichier d\'export. Patientez ...',
    'Grid Export' => '',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Inactive' => 'Inactif',
    'Invalid editable index or model form name' => '',
    'Invalid or bad editable data' => '',
    'JSON' => '',
    'JavaScript Object Notation' => '',
    'Library' => 'Librairie',
    'Microsoft Excel 95+' => '',
    'No data found' => 'Pas de donné trouvé',
    'No valid editable model found' => '',
    'Ok to proceed?' => 'OK pour procéder?',
    'PDF export generated by kartik-v/yii2-grid extension' => '',
    'PDF' => '',
    'Page' => '',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Requête transmise! Vous pouvez fermer cette boite de dialogue après avoir sauvegarder votre fichier téléchargé.',
    'Reset Grid' => 'Reset la grille',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Redimensionner les colonnes de table comme une feuille de calcul en faisant glisser les bords de la colonne.',
    'Show all data' => 'Voir toute les données',
    'Show first page data' => 'Voir la première page de données',
    'Tab Delimited Text' => 'Texte délimité par des tabulations',
    'Text' => '',
    'The CSV export file will be generated for download.' => 'Le fichier d\'export CSV va être généré pour téléchargement',
    'The EXCEL export file will be generated for download.' => 'Le fichier d\'export EXCEL va être généré pour téléchargement',
    'The HTML export file will be generated for download.' => 'Le fichier d\'export HTML va être généré pour téléchargement',
    'The JSON export file will be generated for download.' => 'Le fichier d\'export JSON va être généré pour téléchargement',
    'The PDF export file will be generated for download.' => 'Le fichier d\'export PDF va être généré pour téléchargement',
    'The TEXT export file will be generated for download.' => 'Le fichier d\'export TEXT va être généré pour téléchargement',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Cette page de résumé affiche la SUM (somme) pour le montant des 3 premières cpmp,,e et AVG pour la dernière.',
    'The table header sticks to the top in this demo as you scroll' => 'L\'entête du tableau reste en haut dans cette démo lorsque vous scrollez',
    'There are {totalCount} records. Are you sure you want to display them all?' => '',
    'Update' => 'Mettre à jours',
    'View' => 'Voir',
    'Yii2 Grid Export (PDF)' => '',
    'export' => 'exporter',
    'grid-export' => '',
    'krajee, grid, export, yii2-grid, pdf' => '',
    '© Krajee Yii2 Extensions' => '',
];
