<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Műveletek',
    'Active' => 'Aktív',
    'Add Book' => 'Könyv hozzáadása',
    'All' => 'Összes',
    'Are you sure to delete this {item}?' => 'Biztosan törölni szeretné ezt az {item}?',
    'Book Listing' => 'Könyvek listázása',
    'CSV' => 'CSV',
    'Clear selection' => 'Kijelölés törlése',
    'Collapse' => 'Becsuk',
    'Collapse All' => 'Mindet becsuk',
    'Comma Separated Values' => 'Vesszővel elválasztott értékek',
    'Delete' => 'Törlés',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Kapcsoljon ki minden felugró ablak blokkolót a böngészőjében a sikeres letöltés érdekében.',
    'Download Selected' => 'Kiválasztottak letöltése',
    'Excel' => 'Excel',
    'Expand' => 'kinyit',
    'Expand All' => 'Mindet kinyit',
    'Export' => 'Exportálás',
    'Export All Data' => 'Összes adat exportálása',
    'Export Page Data' => 'Aktuális oldal exportálása',
    'ExportWorksheet' => 'MunkalapExport',
    'Failed to update editable data due to an unknown server error' => 'Nem sikerült szerkeszteni az adatot egy ismeretlen szerverhiba miatt.',
    'Generated' => 'Generálva',
    'Generating the export file. Please wait...' => 'Export fájl előkészítése letöltésre. Várjon...',
    'Grid Export' => 'Táblázat exportálása',
    'HTML' => 'HTML',
    'Inactive' => 'Inaktív',
    'Invalid editable index or model form name' => 'Érvénytelen szerkesztendő azonosító vagy modell',
    'Invalid or bad editable data' => 'Érvénytelen vagy hibás szerkesztendő adat',
    'Library' => 'Könyvtár',
    'No data found' => 'Adat nem található',
    'No valid editable model found' => 'Érvényes szerkeszthető modell nem található',
    'Ok to proceed?' => 'Biztos, hogy folytatja?',
    'PDF export generated by kartik-v/yii2-grid extension' => 'PDF export generálva kartik-v/yii2-grid kiegészítővel',
    'Page' => 'Oldal',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Kérés elküldve! Letöltés után az ablakot bezárhatja.',
    'Reset Grid' => 'Táblázat alaphelyzetbe állítása',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Az oszlopok méretezéséhez húzza az éleket, mint egy táblázatkezelőben!',
    'Show all data' => 'Összes adat mutatása',
    'Show first page data' => 'Első oldal mutatása',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.' => '<b>{begin, number}-{end, number}</b> megjelenítése a(z) <b>{totalCount, number}</b> {totalCount, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'Tab Delimited Text' => 'Tabulátorral tagolt szöveg',
    'Text' => 'Szöveges',
    'The CSV export file will be generated for download.' => 'A CSV fájl előkészítése letöltésre.',
    'The EXCEL export file will be generated for download.' => 'Az EXCEL fájl előkészítése letöltésre.',
    'The HTML export file will be generated for download.' => 'A HTML fájl előkészítése letöltésre.',
    'The JSON export file will be generated for download.' => 'A JSON fájl előkészítése letöltésre.',
    'The PDF export file will be generated for download.' => 'A PDF fájl előkészítése a letöltésre.',
    'The TEXT export file will be generated for download.' => 'A szöveges export fájl előkészítése letöltésre.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Az oldal-összesítő az első 3 érték-oszlop összegét és az utolsó átlagát jeleníti meg.',
    'The table header sticks to the top in this demo as you scroll' => 'A táblázat fejléce az oldal tetejéhez lesz igazítva a görgetés során',
    'There are {totalCount} records. Are you sure you want to display them all?' => 'Összesen {totalCount} sor található. Mindet meg szeretné jeleníteni?',
    'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => 'Összesen <b>{count, number}</b> {count, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'Update' => 'Módosítás',
    'View' => 'Megtekintés',
    'Yii2 Grid Export (PDF)' => 'Yii2 Táblázat Export (PDF)',
    'export' => 'exportálás',
    'grid-export' => 'grid-exportalas',
    'item' => 'elem',
    'items' => 'elemből',
    'items-few' => 'elemből',
    'items-many' => 'elemből',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Kiegészítők',
    '<small>Loading &hellip;</small>' => '',
    'Hyper Text Markup Language' => '',
    'JSON' => '',
    'JavaScript Object Notation' => '',
    'Krajee Solutions' => '',
    'Krajee Yii2 Grid Export Extension' => '',
    'Microsoft Excel 95+' => '',
    'PDF' => '',
    'Portable Document Format' => '',
    'items-acc' => '',
    'krajee, grid, export, yii2-grid, pdf' => '',
];
