<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'प्रक्रिया',
    'Active' => 'सक्रिय',
    'Add Book' => 'पुस्तक को जोड़ें',
    'All' => 'सब',
    'Are you sure to delete this {item}?' => 'आप इस {item} को हटाने के लिए सुनिश्चित हैं?',
    'Book Listing' => 'पुस्तक की सूची',
    'Clear selection' => 'चयन साफ़ करें',
    'Collapse' => 'संकुचित करें',
    'Collapse All' => 'सभी को संकुचित करें',
    'Comma Separated Values' => 'अल्पविराम से अलग किये गए मूल्यों',
    'Delete' => 'मिटायें',
    'Disable any popup blockers in your browser to ensure proper download.' => 'सुनिश्चित करें कि सही डाउनलोड करने के लिए अपने ब्राउज़र में किसी भी पॉपअप ब्लॉकर्स निष्क्रिय करें।',
    'Download Selected' => 'चुने हुए डाउनलोड करें',
    'Expand' => 'विस्तृत करें',
    'Expand All' => 'सभी का विस्तार करें',
    'Export' => 'निर्यात करें',
    'Export All Data' => 'सभी डेटा निर्यात करें',
    'Export Page Data' => 'पेज डेटा निर्यात करें',
    'ExportWorksheet' => 'वर्कशीट निर्यात करें',
    'Failed to update editable data due to an unknown server error' => 'अज्ञात सर्वर जानकारी एक त्रुटि के कारण बदला जा सकता है कि अद्यतन करने में विफल',
    'Generated' => 'जनरेट किया',
    'Generating the export file. Please wait...' => 'निर्यात फ़ाइल जनरेटिंग। कृपया प्रतीक्षा करें...',
    'Grid Export' => 'ग्रिड निर्यात करें',
    'Hyper Text Markup Language' => 'हाइपरटेक्स्ट मार्कअप लैंग्वेज',
    'Inactive' => 'निष्क्रिय',
    'Invalid editable index or model form name' => 'अमान्य अनुक्रमणिका या मॉडल फॉर्म के नाममें परिवर्तन',
    'Invalid or bad editable data' => 'अमान्य या बुरा संपादन योग्य डेटा',
    'JavaScript Object Notation' => 'जावास्क्रिप्ट ऑब्जेक्ट नोटेशन',
    'Library' => 'पुस्तकालय',
    'Microsoft Excel 95+' => 'माइक्रोसॉफ्ट एक्सेल 95+',
    'No data found' => 'कोई डेटा नहीं मिला',
    'No valid editable model found' => 'मॉडल के लिए एक वैध परिवर्तन नहीं मिल सकता है',
    'Ok to proceed?' => 'आगे बढ़ने के लिए ठीक है?',
    'PDF export generated by kartik-v/yii2-grid extension' => 'PDF निर्यात kartik-v/yii2-grid extension के द्वारा किया गया है',
    'Page' => 'पेज',
    'Portable Document Format' => 'पोर्टेबल दस्तावेज़ स्वरूप',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'अनुरोध सबमिट किया गया! आप सुरक्षित रूप से अपने डाउनलोड की गई फ़ाइल को बचाने के बाद इस संवाद को बंद कर सकता है।',
    'Reset Grid' => 'ग्रिड को रीसेट करें',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'कॉलम के किनारों को खींच कर स्तंभों का आकार बदलें।',
    'Select...' => '',
    'Show all data' => 'सभी डेटा दिखाएँ',
    'Show first page data' => 'पहले पेज डेटा दिखाएँ',
    'Tab Delimited Text' => 'टैब सीमांकित पाठ',
    'Text' => 'टेक्स्ट',
    'The CSV export file will be generated for download.' => 'डाउनलोड करने के लिए निर्यात CSV फ़ाइल बना दिया गया है।',
    'The EXCEL export file will be generated for download.' => 'डाउनलोड करने के लिए निर्यात EXCEL फ़ाइल बना दिया गया है।',
    'The HTML export file will be generated for download.' => 'डाउनलोड करने के लिए निर्यात HTML फ़ाइल बना दिया गया है।',
    'The JSON export file will be generated for download.' => 'डाउनलोड करने के लिए निर्यात JSON फ़ाइल बना दिया गया है।',
    'The PDF export file will be generated for download.' => 'डाउनलोड करने के लिए निर्यात PDF फ़ाइल बना दिया गया है।',
    'The TEXT export file will be generated for download.' => 'डाउनलोड करने के लिए निर्यात TEXT फ़ाइल बना दिया गया है।',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'पेज सारांश पहले 3 राशि कॉलम और आखिरी के लिए औसत है।',
    'The table header sticks to the top in this demo as you scroll' => 'टेबल हैडर इस प्रदर्शन में शीर्ष करने के लिए स्टिक के रूप में आप स्क्रॉल करें',
    'There are {totalCount} records. Are you sure you want to display them all?' => 'वहाँ {totalCount} रिकॉर्ड कर रहे हैं। आप उन सब को प्रदर्शित करना चाहते हैं आप सुनिश्चित हैं?',
    'Update' => 'अपडेट करें',
    'View' => 'देखें',
    'Yii2 Grid Export (PDF)' => 'Yii2 ग्रिड निर्यात (PDF)',
    'export' => 'निर्यात करें',
    'grid-export' => 'ग्रिड-निर्यात',
    'item' => 'आइटम',
    'items' => 'आइटमो',
    'krajee, grid, export, yii2-grid, pdf' => 'krajee, ग्रिड, निर्यात, yii2-grid, pdf',
    '<small>Loading &hellip;</small>' => '',
    'CSV' => '',
    'Excel' => '',
    'HTML' => '',
    'JSON' => '',
    'Krajee Solutions' => '',
    'Krajee Yii2 Grid Export Extension' => '',
    'PDF' => '',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.' => '',
    'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => '',
    'items-acc' => '',
    'items-few' => '',
    'items-many' => '',
    '© Krajee Yii2 Extensions' => '',
];
