<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'View'=>'Смотреть',
    'Update'=>'Обновить',
    'Delete'=>'Удалить',
    'Are you sure to delete this item?'=>'Вы действительно хотите удалить?',
    'Actions'=>'Действия',
    'HTML' => 'HTML',
    'CSV' => 'CSV',
    'Text' => 'Text',
    'Excel' => 'Excel',
    'Save as HTML' => 'Сохранить в HTML',
    'Save as CSV' => 'Сохранить в CSV',
    'Save as Text' => 'Сохранить в Text',
    'Save as Excel' => 'Сохранить в Excel',
    'Active' => 'Вкл',
    'Inactive' => 'Выкл',
    'Export' => 'Экспорт',
    'export' => '',
    'grid-export' => '',
    'The HTML export file will be generated for download.' => 'Создать HTML файл для загрузки.',
    'The CSV export file will be generated for download.' => 'Создать CSV файл для загрузки.',
    'The TEXT export file will be generated for download.' => 'Создать TEXT файл для загрузки.',
    'The EXCEL export file will be generated for download.' => 'Создать EXCEL файл для загрузки.',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Чтобы скачать файл, отключите все блокировщики всплывающих окон в вашем браузере.',
    'No data found' => 'Данные не найдены',
    // Demo data
    'Library' => 'Библиотека',
    'Book Listing' => 'Содержимое книги',
    'Add Book' => 'Добавить книгу',
    'Reset Grid' => 'Сбросить сетку',
    'Download Selected' => 'Загрузить выделенное',
    'The table header sticks to the top in this demo as you scroll' => 'В этой демо заголовок таблицы прилипает к верху, пока вы скроллируете',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Сводная страница отобрает сумму 3 первых столбцов и среднее для последнего.',
];
