<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Darbības',
    'Active' => 'Ieslēgt',
    'Add Book' => 'Pievienot grāmatu',
    'All' => 'Viss',
    'Are you sure to delete this {item}?' => 'Vai patiešām vēlaties dzēst šo {item}?',
    'Book Listing' => 'Grāmatas saturs',
    'CSV' => 'CSV',
    'Clear selection' => 'Notīrīt iezīmes',
    'Collapse' => 'Sakļaut',
    'Collapse All' => 'Sakļaut visu',
    'Comma Separated Values' => 'Ar komatiem atdalītas vērtības',
    'Delete' => 'Dzēst',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Atslēgt uznirstošo logu bloķētājus savā pārlūkprogrammā, lai nodrošinātu korektu failu lejuplādi.',
    'Download Selected' => 'Lejupielādēt iezīmēto',
    'Excel' => 'Ekscelis',
    'Expand' => 'Izvērst',
    'Expand All' => 'Izvērst visus',
    'Export' => 'Datu eksports',
    'Export All Data' => 'Eksportēt visus datus',
    'Export Page Data' => 'Eksportēt lapas datus',
    'ExportWorksheet' => 'Eksportēt darba lapu',
    'Generated' => 'Uzģenerēts',
    'Generating the export file. Please wait...' => 'Notiek faila eksportēšana. Lūdzu uzgaidiet...',
    'Grid Export' => 'Tabulas eksports',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'HTML',
    'Inactive' => 'Izslēgts',
    'JSON' => 'JSON',
    'JavaScript Object Notation' => 'JavaScript datu formāts',
    'Library' => 'Bibliotēka',
    'Microsoft Excel 95+' => 'Microsoft Excel 95+',
    'No data found' => 'Dati nav atrasti',
    'Ok to proceed?' => 'Turpināt?',
    'PDF' => 'PDF',
    'Page' => 'Lapa',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Tulīt sāksies faila lejupielāde. Lūdzu uzgaidiet...',
    'Reset Grid' => 'Atstatīt tabulu',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Kolonnu izmēru izmaiņa notiek velkot kolonnu malas.',
    'Show all data' => 'Rādīt visus ierakstus',
    'Show first page data' => 'Rādīt pirmo lapu',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.' => 'Tiek rādīti ieraksti <b>{begin, number}-{end, number}</b> no <b>{totalCount, number}</b> {totalCount, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'Tab Delimited Text' => 'Lauki atdalīti at tabulātoru (TAB)',
    'Text' => 'Teksts',
    'The CSV export file will be generated for download.' => 'Tiks izveidots CSV fails lejupielādēšanai.',
    'The EXCEL export file will be generated for download.' => 'Tiks izveidots EXCEL fails lejupielādēšanai.',
    'The HTML export file will be generated for download.' => 'Tiks izveidots HTML fails lejupielādēšanai.',
    'The JSON export file will be generated for download.' => 'Tiks izveidots JSON fails lejupielādēšanai.',
    'The PDF export file will be generated for download.' => 'Tiks izveidots PDF fails lejupielādēšanai.',
    'The TEXT export file will be generated for download.' => 'Tiks izveidots TEXT fails lejupielādēšanai.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Lapas kopsavilkums attēlo 3 pirmo kolonnu summu un pēdējās kolonnas vidējo vērtību.',
    'There are {totalCount} records. Are you sure you want to display them all?' => 'Kopā ir {totalCount} ieraksti. Vai patiešām vēlaties rādīt visus?',
    'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => 'Kopā <b>{count, number}</b> {count, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'Update' => 'Labot',
    'View' => 'Skatīt',
    'Yii2 Grid Export (PDF)' => 'PDF tabulu eksports Yii2',
    'export' => 'eksports',
    'grid-export' => 'Eksporta tabula',
    'item' => 'ieraksts',
    'items' => 'ieraksti',
    'items-few' => 'ieraksti',
    'items-many' => 'ieraksti',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Paplašinājums',
    'Failed to update editable data due to an unknown server error' => 'Neizdevās atjaunot rediģējamos datus dēļ negaidītas servera kļūdas',
    'Invalid editable index or model form name' => 'Nekorekts rediģējamais indekss vai formas modeļa nosaukums',
    'Invalid or bad editable data' => 'Nekorekti rediģējamie dati',
    'Krajee Solutions' => 'Krajee risinājumi',
    'Krajee Yii2 Grid Export Extension' => 'Krajee Yii2 Grid eksportēšanas paplašinājums',
    'No valid editable model found' => 'Nav atrasts derīgs rediģēšanas modelis',
    'PDF export generated by kartik-v/yii2-grid extension' => 'PDF eksports ģenerēts ar paplašinājumu: kartik-v/yii2-grid',
    'Portable Document Format' => 'Portable Document formāts',
    'The table header sticks to the top in this demo as you scroll' => 'Šajā demo ritināšanas brīdī tabulas virsraksta daļa paliek lapas augšpusē',
    'items-acc' => '',
    'krajee, grid, export, yii2-grid, pdf' => '',
];
