<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Extensions',
    'Actions' => 'Ações',
    'Active' => 'Ativo',
    'Add Book' => 'Adicionar Livro',
    'All' => 'Todos',
    'Are you sure to delete this item?' => 'Tem certeza de que deseja excluir este item?',
    'Book Listing' => 'Listagem dos Livros',
    'Collapse' => '',
    'Collapse All' => '',
    'Comma Separated Values' => 'Valores separados por vírgula',
    'CSV' => 'CSV',
    'Delete' => 'Excluir',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Desative todos os bloqueadores de popup no seu navegador para garantir o download.',
    'Download Selected' => 'Baixar Selecionados',
    'Excel' => 'Excel',
    'Expand' => '',
    'Expand All' => '',
    'Export' => 'Exportar',
    'export' => 'exportar',
    'Export All Data' => '',
    'Export Page Data' => 'Exportação de Dados',
    'ExportWorksheet' => 'Exportar Planilha',
    'Generated' => 'Gerado',
    'Generating the export file. Please wait...' => 'Gerando o arquivo de exportação. Aguarde...',
    'Grid Export' => 'Exportação da Grade',
    'grid-export' => 'grade-exportacao',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'Hyper Text Markup Language',
    'Inactive' => 'Inativo',
    'JavaScript Object Notation' => 'JavaScript Object Notation',
    'JSON' => 'JSON',
    'krajee, grid, export, yii2-grid, pdf' => 'krajee, grid, export, yii2-grid, pdf',
    'Library' => 'Biblioteca',
    'Microsoft Excel 95+' => 'Microsoft Excel 95+',
    'No data found' => 'Nenhum dado encontrado.',
    'Ok to proceed?' => 'Ok para prosseguir?',
    'Page' => 'Página',
    'PDF' => 'PDF',
    'PDF export generated by kartik-v/yii2-grid extension' => 'Exportação de PDF gerado por kartik-v/yii2-grid extension',
    'Portable Document Format' => 'Portable Document Format',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Pedido enviado! Com segurança, você pode fechar esta caixa de diálogo depois de salvar seu arquivo baixado.',
    'Reset Grid' => 'Redefinição de Grade',
    'Show all data' => 'Mostrar todos',
    'Show first page data' => 'Mostrar primeira página',
    'Tab Delimited Text' => '',
    'Text' => 'Texto',
    'The CSV export file will be generated for download.' => 'O arquivo de exportação CSV será gerado para download.',
    'The EXCEL export file will be generated for download.' => 'O arquivo de exportação EXCEL será gerado para download.',
    'The HTML export file will be generated for download.' => 'O arquivo de exportação HTML será gerado para download.',
    'The JSON export file will be generated for download.' => 'Será gerado o arquivo de exportação JSON para download.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'O resumo exibe SUM para os valores das 3 primeiras colunas e AVG para a última.',
    'The PDF export file will be generated for download.' => 'Será gerado o arquivo de exportação do PDF para download.',
    'The table header sticks to the top in this demo as you scroll' => 'O cabeçalho da tabela adere ao topo nesta demonstração enquanto você rola a página',
    'The TEXT export file will be generated for download.' => 'O arquivo de exportação TEXTO será gerado para download.',
    'Update' => 'Alterar',
    'View' => 'Exibir',
    'Yii2 Grid Export (PDF)' => 'Yii2 Grid Export (PDF)',
];
