<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CSV' => 'CSV',
    'Excel' => 'Excel',
    'Failed to update editable data due to an unknown server error' => 'Kon de bewerkbare data niet updaten door een onbekende server fout',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'Hyper Text Markup Language',
    'Invalid editable index or model form name' => 'Ongeldige bewerkbare index of model formulier naam',
    'Invalid or bad editable data' => 'Ongeldige of foutieve bewerkbare data',
    'JSON' => 'JSON',
    'JavaScript Object Notation' => 'JavaScript Object Notation',
    'Microsoft Excel 95+' => 'Microsoft Excel 95+',
    'No valid editable model found' => 'Geen geldige bewerkbare data gevonden',
    'PDF' => 'PDF',
    'Portable Document Format' => 'Portable Document Format',
    'Actions' => 'Acties',
    'Active' => 'Actief',
    'Add Book' => 'Nieuw boek',
    'All' => 'Alles',
    'Are you sure to delete this item?' => 'Weet u zeker dat u dit item wilt verwijderen?',
    'Book Listing' => 'Boekenlijst',
    'Clear selection' => 'Selecties opnieuw',
    'Collapse' => 'Invouwen',
    'Collapse All' => 'Vouw alles in',
    'Comma Separated Values' => 'Komma Gescheiden Waarden (CSV)',
    'Delete' => 'Verwijderen',
    'Disable any popup blockers in your browser to ensure proper download.' => 'De-aktiveer mogelijk aanwezige popup-blockers in uw browser zodat de download werkt.',
    'Download Selected' => 'Geselecteerde downloaden',
    'Expand' => 'Uitvouwen',
    'Expand All' => 'Vouw alles uit',
    'Export' => 'Exporteren',
    'Export All Data' => 'Exporteer alle gegevens',
    'Export Page Data' => 'Exporteer Pagina Gegevens',
    'ExportWorksheet' => 'ExportWerkblad',
    'Generated' => 'Gegenereerd',
    'Generating the export file. Please wait...' => 'Exportbestand aan het generen. Even geduld...',
    'Grid Export' => 'Exporteer Grid',
    'Inactive' => 'Inactief',
    'Library' => 'Bibliotheek',
    'No data found' => 'Geen gegevens gevonden',
    'Ok to proceed?' => 'OK om verder te gaan?',
    'PDF export generated by kartik-v/yii2-grid extension' => 'PDF export gegeneerd door kartik-v/yii2-grid extensie',
    'Page' => 'Pagina',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Aanvraag in behandeling. Na download kan deze dialoog gesloten worden.',
    'Reset Grid' => 'Herstart Grid',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Maak tabelkolommen breder/smaller net als in een spreadsheet door het slepen van de kolomranden.',
    'Show all data' => 'Toon alle gevens',
    'Show first page data' => 'Toon eerste gegevenspagina',
    'Tab Delimited Text' => 'Tab Gescheiden Tekst',
    'Text' => 'Tekst',
    'The CSV export file will be generated for download.' => 'Het CSV exportbestand wordt voor download gegenereerd.',
    'The EXCEL export file will be generated for download.' => 'Het Excel exportbestand wordt voor download gegenereerd.',
    'The HTML export file will be generated for download.' => 'Het HTML exportbestand wordt voor download gegenereerd.',
    'The JSON export file will be generated for download.' => 'Het JSON exportbestand wordt voor download gegenereerd.',
    'The PDF export file will be generated for download.' => 'Het PDF exportbestand wordt voor download gegenereerd.',
    'The TEXT export file will be generated for download.' => 'Het Tekst exportbestand wordt voor download gegenereerd.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'De pagina-samenvatting laat de som (SUM) voor de eerste 3 kolommen en gemiddeld (AVG) voor de laatste zien.',
    'The table header sticks to the top in this demo as you scroll' => 'Als u scrollt, blijft de tabelkop bovenaan in de demo.',
    'There are {totalCount} records. Are you sure you want to display them all?' => 'Er zijn {totalCount} regels. Weet u  zeker dat te allemaal getoond moeten worden?',
    'Update' => 'Bewerken',
    'View' => 'Bekijken',
    'Yii2 Grid Export (PDF)' => 'Yii2 Grid Exporteer (PDF)',
    'export' => 'exporteer',
    'grid-export' => 'grid-exporteer',
    'krajee, grid, export, yii2-grid, pdf' => 'krajee, grid, exporteer, yii2-grid, pdf',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Extensie',
];