<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '© Krajee Yii2 Extensions' => '',
    'Actions' => 'Acties',
    'Active' => 'Actief',
    'Add Book' => 'Nieuw boek',
    'All' => '',
    'Are you sure to delete this item?' => 'Weet je zeker dat je dit item wilt verwijderen?',
    'Book Listing' => 'Boekenlijst',
    'Collapse' => '',
    'Collapse All' => '',
    'Comma Separated Values' => '',
    'CSV' => 'CSV',
    'Delete' => 'Verwijderen',
    'Disable any popup blockers in your browser to ensure proper download.' => 'De-aktiveer mogelijk aanwezige popup-blockers in uw browser zodat de download werkt.',
    'Download Selected' => 'geselecteerde downloaden',
    'Excel' => 'Excel',
    'Expand' => '',
    'Expand All' => '',
    'export' => '',
    'Export' => 'Exporteren',
    'Export All Data' => '',
    'Export Page Data' => 'Export Pagina Gegevens',
    'ExportWorksheet' => 'EksportérWerkblad',
    'Generated' => '',
    'Generating the export file. Please wait...' => '',
    'Grid Export' => '',
    'grid-export' => '',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => '',
    'Inactive' => 'Inactief',
    'JavaScript Object Notation' => '',
    'JSON' => '',
    'krajee, grid, export, yii2-grid, pdf' => '',
    'Library' => 'Bibliotheek',
    'Microsoft Excel 95+' => '',
    'No data found' => 'Geen data gevonden',
    'Ok to proceed?' => '',
    'Page' => '',
    'PDF' => '',
    'PDF export generated by kartik-v/yii2-grid extension' => '',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => '',
    'Reset Grid' => '',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Resize tafel kolommen net als een spreadsheet door het slepen van de kolom randen.',
    'Show all data' => '',
    'Show first page data' => '',
    'Tab Delimited Text' => '',
    'Text' => 'Tekst',
    'The CSV export file will be generated for download.' => 'Het CSV exportbestand wordt voor download gegenereerd.',
    'The EXCEL export file will be generated for download.' => 'Het Excel exportbestand wordt voor download gegenereerd.',
    'The HTML export file will be generated for download.' => 'Het HTML exportbestand wordt voor download gegenereerd.',
    'The JSON export file will be generated for download.' => '',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'De pagina-samenvatting laat SUM voor de eerste 3 kolommen en AVG voor de laatste zien.',
    'The PDF export file will be generated for download.' => '',
    'The table header sticks to the top in this demo as you scroll' => 'Als u scrollt, blijft de tabelkop bovenaan in de demo.',
    'The TEXT export file will be generated for download.' => 'Het Tekst exportbestand wordt voor download gegenereerd.',
    'Update' => 'Bewerken',
    'View' => 'Bekijken',
    'Yii2 Grid Export (PDF)' => '',
];
