<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Clear selection' => 'Auswahl löschen',
    'Collapse' => 'Einklappen',
    'Collapse All' => 'Alle einklappen',
    'Comma Separated Values' => '',
    'Expand' => 'Ausklappen',
    'Expand All' => 'Alle ausklappen',
    'ExportWorksheet' => '',
    'Grid Export' => '',
    'Hyper Text Markup Language' => '',
    'JSON' => '',
    'JavaScript Object Notation' => '',
    'Microsoft Excel 95+' => '',
    'PDF' => '',
    'PDF export generated by kartik-v/yii2-grid extension' => 'PDF-Export generiert durch kartik-v/yii2-grid-extension',
    'Portable Document Format' => '',
    'Tab Delimited Text' => '',
    'Text' => '',
    'Yii2 Grid Export (PDF)' => '',
    'grid-export' => '',
    'krajee, grid, export, yii2-grid, pdf' => '',
    '© Krajee Yii2 Extensions' => '',
    'Actions' => 'Aktionen',
    'Active' => 'Aktiv',
    'Add Book' => 'Neues Buch',
    'All' => 'Alle',
    'Are you sure to delete this item?' => 'Wollen Sie diesen Eintrag wirklich löschen?',
    'Book Listing' => 'Liste der Bücher',
    'CSV' => 'CSV',
    'Delete' => 'Löschen',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Deaktivieren Sie den Popup-Blocker in Ihrem Browser damit der Download funktioniert.',
    'Download Selected' => 'Markierte herunterladen',
    'Excel' => 'Excel',
    'Export' => 'Exportieren',
    'Export All Data' => 'Alle Daten exportieren',
    'Export Page Data' => 'Seiten-Daten exportieren',
    'Generated' => 'Erzeugt',
    'Generating the export file. Please wait...' => 'Erzeuge die Export-Datei. Bitte warten....',
    'HTML' => 'HTML',
    'Inactive' => 'Inaktiv',
    'Library' => 'Bibliothek',
    'No data found' => 'Keine Daten gefunden',
    'Ok to proceed?' => 'Fortfahren?',
    'Page' => 'Seite',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Anfrage übermittelt! Sie können diesen Dialog schließen nachdem Sie die Datei gespeichert haben.',
    'Reset Grid' => 'Grid zurücksetzen',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Ändern Sie die Größe von Tabellenspalten genau wie eine Tabellenkalkulation, indem Sie die Spaltenränder.',
    'Show all data' => 'Alle Daten anzeigen',
    'Show first page data' => 'Daten der ersten Seite anzeigen',
    'The CSV export file will be generated for download.' => 'Die CSV-Export-Datei wird für den Download erstellt.',
    'The EXCEL export file will be generated for download.' => 'Die Excel-Export-Datei wird für den Download erstellt.',
    'The HTML export file will be generated for download.' => 'Die HTML-Export-Datei wird für den Download erstellt.',
    'The JSON export file will be generated for download.' => 'Die JSON-Export-Datei wird für den Download erstellt.',
    'The PDF export file will be generated for download.' => 'Die PDF-Export-Datei wird für den Download erstellt.',
    'The TEXT export file will be generated for download.' => 'Die Text-Export-Datei wird für den Download erstellt.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Die Seite Zusammenfassung wird SUM für die ersten drei und AVG für die letzte Spalte anzeigen.',
    'The table header sticks to the top in this demo as you scroll' => 'Wenn Sie scrollen, hält sich der Tabellenkopf an der Oberkante der Demoseite.',
    'Update' => 'Bearbeiten',
    'View' => 'Anzeigen',
    'export' => 'exportieren',
];
