<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Actes',
    'Active' => 'Actif',
    'Add Book' => 'Ajouter un livre',
    'All' => 'Tous',
    'Are you sure to delete this {item}?' => 'Êtes vous sûr de vouloir supprimer cet {item}?',
    'Book Listing' => 'Liste de livres',
    'CSV' => 'CSV',
    'Clear selection' => 'Effacer la sélection',
    'Collapse' => 'Replier',
    'Collapse All' => 'Replier tout',
    'Comma Separated Values' => 'Valeurs séparées par des virgules',
    'Delete' => 'Supprimer',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Désactiver tous les bloqueurs de publicité pour assurer un téléchargement correct',
    'Download Selected' => 'Télécharger les éléments sélectionnés',
    'Excel' => 'Excel',
    'Expand' => 'Déplier',
    'Expand All' => 'Déplier tout',
    'Export' => 'Exporter',
    'Export All Data' => 'Exporter toutes les données',
    'Export Page Data' => 'Exporter les données de la page',
    'ExportWorksheet' => 'Exporter la feuille',
    'Failed to update editable data due to an unknown server error' => 'Échec de la mise à jour des données modifiables en raison d\'une erreur de serveur inconnue.',
    'Generated' => 'Généré',
    'Generating the export file. Please wait...' => 'Génération du fichier d\'export. Patientez ...',
    'Grid Export' => 'Exportation de la grille',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'Langage Signalétique Hyper Text',
    'Inactive' => 'Inactif',
    'Invalid editable index or model form name' => 'L\'index modifiable ou le nom du modèle de formulaire est invalide',
    'Invalid or bad editable data' => 'Les données modifiables sont incorrectes',
    'JSON' => 'JSON ',
    'JavaScript Object Notation' => 'Notation d\'objet JavaScript',
    'Library' => 'Bibliothèque',
    'Microsoft Excel 95+' => 'Microsoft Excel 95+',
    'No data found' => 'Aucune donnée trouvée',
    'No valid editable model found' => 'Aucun modèle modifiable valide n\'a été trouvé',
    'Ok to proceed?' => 'OK pour procéder?',
    'PDF' => 'PDF',
    'PDF export generated by kartik-v/yii2-grid extension' => 'Export PDF généré par l\'extension kartik-v/yii2-grid',
    'Page' => 'Page',
    'Portable Document Format' => 'Portable Document Format',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Requête transmise! Vous pouvez fermer cette boite de dialogue après avoir sauvegardé votre fichier téléchargé.',
    'Reset Grid' => 'Réinitialiser la grille',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Redimensionner les colonnes de table comme une feuille de calcul en faisant glisser les bords de la colonne.',
    'Show all data' => 'Voir toutes les données',
    'Show first page data' => 'Voir la première page de données',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.' => 'Affichage de <b>{begin, number}-{end, number}</b> sur <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.',
    'Tab Delimited Text' => 'Texte délimité par des tabulations',
    'Text' => 'Texte',
    'The CSV export file will be generated for download.' => 'Le fichier d\'export CSV va être généré pour téléchargement',
    'The EXCEL export file will be generated for download.' => 'Le fichier d\'export EXCEL va être généré pour téléchargement',
    'The HTML export file will be generated for download.' => 'Le fichier d\'export HTML va être généré pour téléchargement',
    'The JSON export file will be generated for download.' => 'Le fichier d\'export JSON va être généré pour téléchargement',
    'The PDF export file will be generated for download.' => 'Le fichier d\'export PDF va être généré pour téléchargement',
    'The TEXT export file will be generated for download.' => 'Le fichier d\'export TEXT va être généré pour téléchargement',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Cette page de résumé affiche SUM (la somme) pour le montant des 3 premières colonnes et AVG (moyenne) pour la dernière.',
    'The table header sticks to the top in this demo as you scroll' => 'L\'entête du tableau reste en haut dans cette démo lorsque vous scrollez',
    'There are {totalCount} records. Are you sure you want to display them all?' => 'Il y a {totalCount} lignes. Êtes-vous sûr de vouloir les afficher toutes?',
    'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => 'Total <b>{count, number}</b> {count, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'Update' => 'Mettre à jour',
    'View' => 'Voir',
    'Yii2 Grid Export (PDF)' => 'Yii2 Grid Export (PDF)',
    'export' => 'exporter',
    'grid-export' => 'grid-export',
    'item' => 'élément',
    'items' => 'éléments',
    'items-few' => 'éléments',
    'krajee, grid, export, yii2-grid, pdf' => 'krajee, grille, exportation, yii2-grid, pdf',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Extensions',
    'Krajee Solutions' => '',
    'Krajee Yii2 Grid Export Extension' => '',
    'items-acc' => '',
    'items-many' => '',
];
