<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Дії',
    'Active' => 'Вкл',
    'Add Book' => 'Додати книгу',
    'All' => 'Все',
    'Are you sure to delete this {item}?' => 'Ви дійсно хочете видалити даний {item}?',
    'Book Listing' => 'Зміст книги',
    'CSV' => 'CSV',
    'Clear selection' => 'Видалити виділення',
    'Collapse' => 'Згорнути',
    'Collapse All' => 'Згорнути все',
    'Comma Separated Values' => 'Данні розділені комою',
    'Delete' => 'Удалить',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Щоб скачати файл, вимкніть блокування спливаючих вікон у вашому браузері.',
    'Download Selected' => 'Завантажити обране',
    'Excel' => 'Excel',
    'Expand' => 'Розгорнути',
    'Expand All' => 'Розгорнути все',
    'Export' => 'Експорт',
    'Export All Data' => 'Експортувати всі данні',
    'Export Page Data' => 'Експорт даних з цієї сторінки',
    'ExportWorksheet' => 'ЕкспортPобочийЛист',
    'Generated' => 'Згенеровано',
    'Generating the export file. Please wait...' => 'Файл для експорту генерується. Будь ласка зачекайте...',
    'Grid Export' => 'Експорт таблиці',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'HTML',
    'Inactive' => 'Вимк',
    'JSON' => 'JSON',
    'JavaScript Object Notation' => 'Формат данних JavaScript',
    'Library' => 'Бібліотека',
    'Microsoft Excel 95+' => 'Microsoft Excel 95+',
    'No data found' => 'Данні не знайдені',
    'Ok to proceed?' => 'Продовжити?',
    'PDF' => 'PDF',
    'PDF export generated by kartik-v/yii2-grid extension' => 'PDF згенерований розширенням kartik-v/yii2-grid',
    'Page' => 'Сторінка',
    'Portable Document Format' => 'Міжплатформенний формат електронних документів',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Зараз почнеться завантаження файлу. Будь ласка зачекайте...',
    'Reset Grid' => 'Скинути таблицю',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Зміна розміру стовпців таблиці відбувається так само, як таблиці - перетягуючи краю стовпців',
    'Show all data' => 'Показати всі записи',
    'Show first page data' => 'Показати першу сторінку',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.' => 'Показані <b>{begin, number}-{end, number}</b> із <b>{totalCount, number}</b> {totalCount, plural, one{запису} other{записів}}.',
    'Tab Delimited Text' => 'Текст розділений пробілами (табами)',
    'Text' => 'Текст',
    'The CSV export file will be generated for download.' => 'Буде згенеровано CSV файл для завантаження.',
    'The EXCEL export file will be generated for download.' => 'Буде згенеровано EXCEL файл для завантаження.',
    'The HTML export file will be generated for download.' => 'Буде згенеровано HTML файл для завантаження.',
    'The JSON export file will be generated for download.' => 'Буде згенеровано JSON файл для завантаження.',
    'The PDF export file will be generated for download.' => 'Буде згенеровано PDF файл для завантаження.',
    'The TEXT export file will be generated for download.' => 'Буде згенеровано текстовий файл для завантаження.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Зведена сторінка відображає суму 3 перших стовпців і середнє для останнього.',
    'The table header sticks to the top in this demo as you scroll' => 'У цій демо-версії заголовок таблиці прилипає до верху, поки ви скролите',
    'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => 'Всього <b>{count, number}</b> {count, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'Update' => 'Змінити',
    'View' => 'Перегляд',
    'Yii2 Grid Export (PDF)' => 'PDF експорт таблиці Yii2',
    'export' => 'експорт',
    'grid-export' => 'Експорт таблиці',
    'item' => 'запису',
    'items' => 'записи',
    'items-few' => 'записи',
    'items-many' => 'записів',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Розширення',
    'Failed to update editable data due to an unknown server error' => '',
    'Invalid editable index or model form name' => '',
    'Invalid or bad editable data' => '',
    'Krajee Solutions' => '',
    'Krajee Yii2 Grid Export Extension' => '',
    'No valid editable model found' => '',
    'There are {totalCount} records. Are you sure you want to display them all?' => 'Всього вибрано {totalCount} записів. Ви дійсно хочете показати їх всі?',
    'items-acc' => '',
    'krajee, grid, export, yii2-grid, pdf' => '',
];
