<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Ações',
    'Active' => 'Ativo',
    'Add Book' => 'Adicionar Livro',
    'All' => 'Todos',
    'Are you sure to delete this {item}?' => 'Tem certeza de que deseja excluir este {item}?',
    'Book Listing' => 'Listagem dos Livros',
    'CSV' => 'CSV',
    'Clear selection' => 'Limpar seleção',
    'Collapse' => 'Contrair',
    'Collapse All' => 'Contrair Todos',
    'Comma Separated Values' => 'Valores Separados por Vírgula',
    'Delete' => 'Excluir',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Desative todos os bloqueadores de popup no seu navegador para garantir o download.',
    'Download Selected' => 'Baixar Selecionados',
    'Excel' => 'Excel',
    'Expand' => 'Expandir',
    'Expand All' => 'Expandir Todos',
    'Export' => 'Exportar',
    'Export All Data' => 'Exportar Tudo',
    'Export Page Data' => 'Exportar Dados da Página',
    'ExportWorksheet' => 'Exportar Planilha',
    'Generated' => 'Gerado',
    'Generating the export file. Please wait...' => 'Gerando o arquivo de exportação. Aguarde...',
    'Grid Export' => 'Exportação da Grade',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'Hyper Text Markup Language',
    'Inactive' => 'Inativo',
    'Invalid editable index or model form name' => 'Índice editável inválido ou nome do form do model inválido',
    'Invalid or bad editable data' => 'Dados editáveis ruins ou inválidos',
    'JSON' => 'JSON',
    'JavaScript Object Notation' => 'JavaScript Object Notation',
    'Library' => 'Biblioteca',
    'Microsoft Excel 95+' => 'Microsoft Excel 95+',
    'No data found' => 'Nenhum dado encontrado.',
    'No valid editable model found' => 'Não foi encontrado um model editável válido',
    'Ok to proceed?' => 'Ok para prosseguir?',
    'PDF' => 'PDF',
    'PDF export generated by kartik-v/yii2-grid extension' => 'Exportação de PDF gerado por kartik-v/yii2-grid extension',
    'Page' => 'Página',
    'Portable Document Format' => 'Portable Document Format',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Pedido enviado! Você pode fechar esta caixa de diálogo com segurança após baixar o arquivo.',
    'Reset Grid' => 'Redefinir Grade',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Redimensionar colunas da tabela como uma planilha arrastando as bordas das colunas.',
    'Show all data' => 'Mostrar todos os registros',
    'Show first page data' => 'Mostrar os registros da primeira página',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.' => 'A exibir <b>{begin, number}-{end, number}</b> de <b>{totalCount, number}</b> {totalCount, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'Tab Delimited Text' => 'Texto Delimitado por Tabulação',
    'Text' => 'Texto',
    'The CSV export file will be generated for download.' => 'O arquivo de exportação CSV será gerado para download.',
    'The EXCEL export file will be generated for download.' => 'O arquivo de exportação EXCEL será gerado para download.',
    'The HTML export file will be generated for download.' => 'O arquivo de exportação HTML será gerado para download.',
    'The JSON export file will be generated for download.' => 'Será gerado o arquivo de exportação JSON para download.',
    'The PDF export file will be generated for download.' => 'Será gerado o arquivo de exportação do PDF para download.',
    'The TEXT export file will be generated for download.' => 'O arquivo de exportação TEXTO será gerado para download.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'O resumo exibe SUM (soma) para os valores das 3 primeiras colunas e AVG (média) para a última.',
    'The table header sticks to the top in this demo as you scroll' => 'O cabeçalho da tabela adere ao topo nesta demonstração enquanto você rola a página',
    'There are {totalCount} records. Are you sure you want to display them all?' => 'Existem {totalCount} registros. Tem certeza de que deseja exibir todos?',
    'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => 'Total <b>{count, number}</b> {count, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'Update' => 'Alterar',
    'View' => 'Exibir',
    'Yii2 Grid Export (PDF)' => 'Yii2 Grid Export (PDF)',
    'export' => 'exportar',
    'grid-export' => 'grade-exportacao',
    'item' => 'item',
    'items' => 'itens',
    'items-few' => 'itens',
    'items-many' => 'itens',
    'krajee, grid, export, yii2-grid, pdf' => 'krajee, grid, export, yii2-grid, pdf',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Extensions',
    '<small>Loading &hellip;</small>' => '',
    'Failed to update editable data due to an unknown server error' => '',
    'Krajee Solutions' => '',
    'Krajee Yii2 Grid Export Extension' => '',
    'items-acc' => '',
];
