<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Akce',
    'Active' => 'Aktivní',
    'Add Book' => 'Přidat knihu',
    'All' => 'Vše',
    'Are you sure to delete this item?' => 'Opravdu si přejete smazat tuto položku?',
    'Book Listing' => 'Seznam knih',
    'CSV' => 'CSV',
    'Clear selection' => 'Zrušit výběr',
    'Collapse' => 'Sbalit',
    'Collapse All' => 'Sbalit vše',
    'Comma Separated Values' => 'Text oddělený středníkem',
    'Delete' => 'Smazat',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Povolte vyskakovací okna pro umožnění exportu.',
    'Download Selected' => 'Stáhnout vybrané',
    'Excel' => 'Excel',
    'Expand' => 'Rozbalit',
    'Expand All' => 'Exportovat vše',
    'Export' => 'Export',
    'Export All Data' => 'Exportovat všechna stránky',
    'Export Page Data' => 'Exportovat data stránky',
    'ExportWorksheet' => 'Exportovat Soubor',
    'Generated' => 'Vygenerováno',
    'Generating the export file. Please wait...' => 'Generování souboru. Počkejte prosím...',
    'Grid Export' => 'Export tabulky',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'HTML',
    'Inactive' => 'Neaktivní',
    'JSON' => 'JSON',
    'JavaScript Object Notation' => 'JSON',
    'Library' => 'Knihovna',
    'Microsoft Excel 95+' => 'Microsoft Excel 95+',
    'No data found' => 'Nenalezena žádná data',
    'Ok to proceed?' => 'Pokračovat?',
    'PDF' => 'PDF',
    'PDF export generated by kartik-v/yii2-grid extension' => 'PDF',
    'Page' => 'Strana',
    'Portable Document Format' => 'PDF',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Požadavek byl zpracován. Po uložení souboru můžete bezpečně zavřít toto okno.',
    'Reset Grid' => 'Obnovit tabulku',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Nastavte velikost sloupce tažením myší stejně jako v excelu.',
    'Show all data' => 'Zobrazit všechna data',
    'Show first page data' => 'Zobrazit data první stránky',
    'Tab Delimited Text' => 'Text oddělený tabelátory',
    'Text' => 'Text',
    'The CSV export file will be generated for download.' => 'CSV soubor bude vygenerován.',
    'The EXCEL export file will be generated for download.' => 'Excel soubor bude vygenerován.',
    'The HTML export file will be generated for download.' => 'HTML soubor bude vygenerován.',
    'The JSON export file will be generated for download.' => 'JSON soubor bude vygenerován.',
    'The PDF export file will be generated for download.' => 'PDF soubor bude vygenerován.',
    'The TEXT export file will be generated for download.' => 'Text soubor bude vygenerován.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Shrnutí stránky zobrazuje součet pro prvé 3 číselné sloupce a průměr pro poslední sloupec.',
    'The table header sticks to the top in this demo as you scroll' => 'Záhlaví tabulky je během rolování nahoře ukotveno',
    'Update' => 'Obnovit',
    'View' => 'Zobrazit',
    'Yii2 Grid Export (PDF)' => 'Yii2 Grid Export (PDF)',
    'export' => 'export',
    'grid-export' => 'grid-export',
    'krajee, grid, export, yii2-grid, pdf' => 'krajee, grid, export, yii2-grid, pdf',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Extensions',
];