<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Aksi',
    'Active' => 'Aktif',
    'Add Book' => 'Tambah Buku',
    'All' => 'Semua',
    'Are you sure to delete this {item}?' => 'Apakah anda setuju akan menghapus {item} ini?',
    'Book Listing' => 'Daftar Buku',
    'Clear selection' => 'Bersihkan seleksi',
    'Delete' => 'Hapus',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Nonaktifkan semua popup blocker di browser anda untuk memastikan unduhan yang benar.',
    'Download Selected' => 'Unduhan dipilih',
    'Generating the export file. Please wait...' => 'Menghasilkan file ekspor. Silakan tunggu ...',
    'No data found' => 'Data tidak ditemukan',
    'Ok to proceed?' => 'Ok untuk memproses',
    'Page' => 'Halaman',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Permintaan disampaikan! Anda mungkin sudah bisa menutup dialog ini setelah menyimpan berkas yang anda unduh.',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Mengubah ukuran kolom tabel seperti spreadsheet dengan menyeret tepi kolom.',
    'Select...' => '',
    'Show all data' => 'Tampilkan semua data',
    'Show first page data' => 'Tampilkan data halaman pertama',
    'Text' => 'Teks',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Ringkasan halaman menampilkan jumlah untuk 3 kolom pertama jumlah dan rata-rata untuk yang terakhir.',
    'The table header sticks to the top in this demo as you scroll' => 'Table header tetap ke atas dalam demo ini sebagai saat anda menggulir',
    'Update' => 'Ubah',
    'View' => 'Lihat',
    'items-few' => 'items',
    'items-many' => 'items',
    '<small>Loading &hellip;</small>' => '',
    'CSV' => '',
    'Collapse' => '',
    'Collapse All' => '',
    'Comma Separated Values' => '',
    'Excel' => '',
    'Expand' => '',
    'Expand All' => '',
    'Export' => '',
    'Export All Data' => '',
    'Export Page Data' => '',
    'ExportWorksheet' => '',
    'Failed to update editable data due to an unknown server error' => '',
    'Generated' => '',
    'Grid Export' => '',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Inactive' => '',
    'Invalid editable index or model form name' => '',
    'Invalid or bad editable data' => '',
    'JSON' => '',
    'JavaScript Object Notation' => '',
    'Krajee Solutions' => '',
    'Krajee Yii2 Grid Export Extension' => '',
    'Library' => '',
    'Microsoft Excel 95+' => '',
    'No valid editable model found' => '',
    'PDF' => '',
    'PDF export generated by kartik-v/yii2-grid extension' => '',
    'Portable Document Format' => '',
    'Reset Grid' => '',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.' => '',
    'Tab Delimited Text' => '',
    'The CSV export file will be generated for download.' => '',
    'The EXCEL export file will be generated for download.' => '',
    'The HTML export file will be generated for download.' => '',
    'The JSON export file will be generated for download.' => '',
    'The PDF export file will be generated for download.' => '',
    'The TEXT export file will be generated for download.' => '',
    'There are {totalCount} records. Are you sure you want to display them all?' => '',
    'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => '',
    'Yii2 Grid Export (PDF)' => '',
    'export' => '',
    'grid-export' => '',
    'item' => '',
    'items' => '',
    'items-acc' => '',
    'krajee, grid, export, yii2-grid, pdf' => '',
    '© Krajee Yii2 Extensions' => '',
    'The {type} export file will be generated for download.' => '@@File {type} yang diekspor akan dibuat untuk diunduh.@@',
    'Yii2 Grid Export {type}' => '@@Yii2 Grid Export {type}@@',
];
