<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure to delete this {item}?' => 'Ar tikrai norite ištrinti šį {item}?',
    'CSV' => '',
    'Excel' => '',
    'ExportWorksheet' => '',
    'Failed to update editable data due to an unknown server error' => '',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Invalid editable index or model form name' => '',
    'Invalid or bad editable data' => '',
    'JSON' => '',
    'Microsoft Excel 95+' => '',
    'No valid editable model found' => '',
    'PDF' => '',
    'Portable Document Format' => '',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.'  =>  'Rodomi rezultatai <b>{begin, number}-{end, number}</b> iš <b>{totalCount, number}</b> {totalCount, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'Tab Delimited Text' => '',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => '',
    'The table header sticks to the top in this demo as you scroll' => '',
    'There are {totalCount} records. Are you sure you want to display them all?' => '',
    'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => 'Iš viso <b>{count, number}</b> {count, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'Yii2 Grid Export (PDF)' => '',
    'grid-export' => '',
    'item' => 'elementas',
    'items' => 'elementų',
    'items-few' => 'elementai',
    'items-many' => 'elementų',
    'krajee, grid, export, yii2-grid, pdf' => '',
    'Actions' => 'Veiksmai',
    'Active' => 'Aktyvus',
    'Add Book' => 'Pridėti knygą',
    'All' => 'Visi',
    'Book Listing' => 'Knygų sąrašas',
    'Clear selection' => 'Anuliuoti pasirinkimus',
    'Collapse' => 'Paslėpti',
    'Collapse All' => 'Paslėpti visus',
    'Comma Separated Values' => 'Kableliais atskirtos reikšmės',
    'Delete' => 'Ištrinti',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Išjūnkite visas iškylančiųjų langų blokavimo programas, jog užtikrintumėt tinkamą sistemos veikima.',
    'Download Selected' => 'Atsisiųsti pasirinktus',
    'Expand' => 'Rodyti išplėstinius duomenis',
    'Expand All' => 'Rodyti visus išplėstinius duomenis',
    'Export' => 'Eksportuoti',
    'Export All Data' => 'Eksportuoti visus duomenis',
    'Export Page Data' => 'Eksportuoti puslapio duomenis',
    'Generated' => 'Sugeneruota',
    'Generating the export file. Please wait...' => 'Generuojamas eksportavimo failas. Prašome palaukti.',
    'Grid Export' => 'Išdėstymo eksportavimas',
    'Inactive' => 'Neaktyvus',
    'JavaScript Object Notation' => 'Javascript Objekto Notacija',
    'Library' => 'Biblioteka',
    'No data found' => 'Nerasta duomenų',
    'Ok to proceed?' => 'Tęsti?',
    'PDF export generated by kartik-v/yii2-grid extension' => 'PDF exportavimas generuotas "kartik-v/yii2-grid extension" valdiklio pagalba ',
    'Page' => 'Puslapis',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Užklausa išsiųsta. Galite saugiai uždaryti šį langą kai išsisaugosit failą',
    'Reset Grid' => 'Atstatyti išdėstymą',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Galite reguliuoti lentelės stulpelių dydi taip pat kaip Microsoft Excel programoje',
    'Show all data' => 'Rodyti visus duomenis',
    'Show first page data' => 'Rodyti pirmo puslapio duomenis',
    'Text' => 'Tekstas',
    'The CSV export file will be generated for download.' => 'CSV eksportavimo failas bus sugeneruotas jūsų atsisiuntimui',
    'The EXCEL export file will be generated for download.' => 'EXCEL eksportavimo failas bus sugeneruotas jūsų atsisiuntimui',
    'The HTML export file will be generated for download.' => 'HTML eksportavimo failas bus sugeneruotas jūsų atsisiuntimui',
    'The JSON export file will be generated for download.' => 'JSON eksportavimo failas bus sugeneruotas jūsų atsisiuntimui',
    'The PDF export file will be generated for download.' => 'PDF eksportavimo failas bus sugeneruotas jūsų atsisiuntimui',
    'The TEXT export file will be generated for download.' => 'TEXT eksportavimo failas bus sugeneruotas jūsų atsisiuntimui',
    'Update' => 'Atnaujinti',
    'View' => 'Peržiūrėti',
    'export' => 'eksportuoti',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Valdikliai',
];
