<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Ενέργειες',
    'Active' => 'Ενεργό',
    'Add Book' => 'Προσθήκη βιβλίου',
    'All' => 'Όλα',
    'Are you sure to delete this item?' => 'Είσαι σίγουρος για την διαγραφή του αντικειμένου',
    'Book Listing' => 'Λίστα Βιβλίων',
    'CSV' => 'csv',
    'Clear selection' => 'Εκκαθάρισης επιλογών',
    'Collapse' => 'Κλείσιμο',
    'Collapse All' => 'Κλείσιμο όλων',
    'Comma Separated Values' => 'τιμές χωρισμένες με κόμμα',
    'Delete' => 'Διαγραφή',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Απενεργοποίηση προγραμμάτων για popup στο πρόγραμμα ιστοσελίδων',
    'Download Selected' => 'Κατέβασμα επιλεγμένων',
    'Excel' => 'Excel',
    'Expand' => 'Επέκταση',
    'Expand All' => 'Επέκταση όλων',
    'Export' => 'Εξαγωγή',
    'Export All Data' => 'Εξαγωγή όλων των δεδομένων',
    'Export Page Data' => 'Εξαγωγή δεδομένων σελίδας',
    'ExportWorksheet' => 'Εξαγωγή φύλλου εργασίας',
    'Generated' => 'Παραγώμενα',
    'Generating the export file. Please wait...' => 'Το αρχείο εξαγωγής δημιουργείται. Παρακαλώ περιμένετε',
    'Grid Export' => 'Εξαγωγή πίνακα',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'Γλώσσα υπερκειμένου',
    'Inactive' => 'Ανενεργό',
    'JSON' => 'Json',
    'JavaScript Object Notation' => '',
    'Library' => 'Βιβλιοθήκη',
    'Microsoft Excel 95+' => '',
    'No data found' => 'Δεν βρέθηκαν δεδομένα',
    'Ok to proceed?' => 'Να προχωρήσουμε;',
    'PDF' => '',
    'PDF export generated by kartik-v/yii2-grid extension' => '',
    'Page' => 'Σελίδα',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Η αίτηση καταχωρήθηκε! Μπορείτε να κλείσετε με ασφάλεια αυτό τον διάλογο αφού αποθηκεύσετε το αρχείο που κατεβάσατε',
    'Reset Grid' => 'Αρχικοποίηση πίνακα',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Αναδιάταξη των στηλών πίνακα όως θα κάνετε και με ένα φύλλο εργασίας τραβώντας τις άκρες των στηλών',
    'Show all data' => 'Δείξε όλα τα δεδομένα',
    'Show first page data' => 'Δείξε τα δεδομένα της πρώτης σελίδας',
    'Tab Delimited Text' => '',
    'Text' => 'Κείμενο',
    'The CSV export file will be generated for download.' => 'Το αρχείο csv θα παραχθεί ώστε να κατεβεί',
    'The EXCEL export file will be generated for download.' => 'Το αρχείο EXCEL θα παραχθεί ώστε να κατεβεί',
    'The HTML export file will be generated for download.' => 'Το αρχείο HTML θα παραχθεί ώστε να κατεβεί',
    'The JSON export file will be generated for download.' => 'Το αρχείο JSON θα παραχθεί ώστε να κατεβεί',
    'The PDF export file will be generated for download.' => 'Το αρχείο PDF θα παραχθεί ώστε να κατεβεί',
    'The TEXT export file will be generated for download.' => 'Το αρχείο TEXT θα παραχθεί ώστε να κατεβεί',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => '',
    'The table header sticks to the top in this demo as you scroll' => '',
    'Update' => 'Ενημέρωση',
    'View' => 'Προβολή',
    'Yii2 Grid Export (PDF)' => '',
    'export' => 'εξαγωγή',
    'grid-export' => 'εξαγωγή πίνακα',
    'krajee, grid, export, yii2-grid, pdf' => '',
    '© Krajee Yii2 Extensions' => '',
];
