<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure to delete this {item}?' => '確定刪除此紀錄 {item}?',
    'Failed to update editable data due to an unknown server error' => '',
    'Invalid editable index or model form name' => '',
    'Invalid or bad editable data' => '',
    'No valid editable model found' => '',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.'  =>  '第 <b>{begin, number}-{end, number}</b> 項，共 <b>{totalCount, number}</b> 項資料.',
    'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => '總計 <b>{count, number}</b> 項資料。',
    'item' => '',
    'items' => '',
    'items-few' => 'items',
    'items-many' => 'items',
    'Actions' => '動作',
    'Active' => '以激活',
    'Add Book' => '新增書籍',
    'All' => '全部',
    'Book Listing' => '書籍列表',
    'CSV' => 'CSV',
    'Clear selection' => '清除選擇',
    'Collapse' => '收合',
    'Collapse All' => '全部收合',
    'Comma Separated Values' => '以逗號分割的值',
    'Delete' => '刪除',
    'Disable any popup blockers in your browser to ensure proper download.' => '禁用所有阻止彈出視窗的瀏覽器設定以確保下載成功',
    'Download Selected' => '已選擇下載項',
    'Excel' => 'Excel',
    'Expand' => '展開',
    'Expand All' => '全部展開',
    'Export' => '匯出',
    'Export All Data' => '匯出所有數據',
    'Export Page Data' => '匯出本頁數據',
    'ExportWorksheet' => '匯出工作表',
    'Generated' => '已經生成',
    'Generating the export file. Please wait...' => '正在匯出文件,請稍後...',
    'Grid Export' => '匯出表格',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => '網頁標記語言',
    'Inactive' => '未激活',
    'JSON' => 'JSON',
    'JavaScript Object Notation' => 'JavaScript對象符號',
    'Library' => '函式庫',
    'Microsoft Excel 95+' => '微軟Excel版本95以上',
    'No data found' => '未找到數據',
    'Ok to proceed?' => '確定執行操作?',
    'PDF' => 'PDF',
    'PDF export generated by kartik-v/yii2-grid extension' => '匯出由kartik-v/yii2-grid擴展生成的PDF',
    'Page' => '頁',
    'Portable Document Format' => '可攜的文件格式',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => '請求已經提交,您可以在文件下載成功後關閉此對話.',
    'Reset Grid' => '重置表格',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => '拖動表格邊緣來進行縮放',
    'Show all data' => '顯示所有數據',
    'Show first page data' => '顯示第一頁數據',
    'Tab Delimited Text' => 'TAB 分割的文件',
    'Text' => '本文',
    'The CSV export file will be generated for download.' => '將會匯出CSV文件以供下载',
    'The EXCEL export file will be generated for download.' => '將會匯出EXCEL文件以供下载',
    'The HTML export file will be generated for download.' => '將會匯出HTML文件以供下载',
    'The JSON export file will be generated for download.' => '將會匯出JSON文件以供下载',
    'The PDF export file will be generated for download.' => '將會匯出PDF文件以供下载',
    'The TEXT export file will be generated for download.' => '將會匯出文本文件以供下载',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => '頁面概要顯示前三列的合以及最後一列的平均值',
    'The table header sticks to the top in this demo as you scroll' => '此範例表頭將在你滾動頁面時固定在頂部',
    'There are {totalCount} records. Are you sure you want to display them all?' => '有{totalCount}筆紀錄。你確定要顯示所有資料嗎?',
    'Update' => '更新',
    'View' => '查看',
    'Yii2 Grid Export (PDF)' => '由Yii2 Grid匯出的PDF',
    'export' => '匯出',
    'grid-export' => '匯出表格',
    'krajee, grid, export, yii2-grid, pdf' => 'krajee, grid, export, yii2-grid, pdf',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Extensions',
];
