<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '© Krajee Yii2 Extensions' => '',
    'Actions' => 'Hành động',
    'Active' => 'Kích hoạt',
    'Add Book' => 'Thêm sách',
    'All' => '',
    'Are you sure to delete this item?' => 'Bạn có chắc là sẽ xóa mục này không?',
    'Book Listing' => 'Liệt kê sách',
    'Comma Separated Values' => '',
    'CSV' => '',
    'Delete' => 'Xóa',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Tắt các trình chặn popup trong trình duyệt để việc tải về được suôn sẻ.',
    'Download Selected' => 'Tải về lựa chọn',
    'Excel' => '',
    'export' => '',
    'Export' => 'Xuất',
    'Export All Data' => '',
    'Export Page Data' => 'Xuất dữ liệu trang',
    'ExportWorksheet' => 'Xuất bảng tính',
    'Generated' => '',
    'Generating the export file. Please wait...' => '',
    'Grid Export' => '',
    'grid-export' => '',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Inactive' => 'Ko kích hoạt',
    'JavaScript Object Notation' => '',
    'JSON' => '',
    'krajee, grid, export, yii2-grid, pdf' => '',
    'Library' => 'Thư viện',
    'Microsoft Excel 95+' => '',
    'No data found' => 'Không tìm thấy dữ liệu',
    'Ok to proceed?' => '',
    'Page' => '',
    'PDF' => '',
    'PDF export generated by kartik-v/yii2-grid extension' => '',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => '',
    'Reset Grid' => 'Thiết lập lại lưới',
    'Show all data' => '',
    'Show first page data' => '',
    'Tab Delimited Text' => '',
    'Text' => '',
    'The CSV export file will be generated for download.' => 'Tập tin CSV sẽ được xuất để tải về.',
    'The EXCEL export file will be generated for download.' => 'Tập tin EXCEL sẽ được xuất để tải về.',
    'The HTML export file will be generated for download.' => 'Tập tin HTML sẽ được xuất để tải về.',
    'The JSON export file will be generated for download.' => '',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Dòng tổng hợp hiển thị SUM cho các giá trị 3 cột đầu và AVG cho cột cuối.',
    'The PDF export file will be generated for download.' => '',
    'The table header sticks to the top in this demo as you scroll' => 'Trong bản demo này, tiêu đề của bảng luôn được hiển thị phía trên khi trang được cuộn xuống',
    'The TEXT export file will be generated for download.' => 'Tập tin TEXT sẽ được xuất để tải về.',
    'Update' => 'Sửa',
    'View' => 'Xem',
    'Yii2 Grid Export (PDF)' => '',
];
