<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All' => 'Toàn bộ',
    'CSV' => '',
    'Clear selection' => 'Hủy bỏ lựa chọn',
    'Collapse' => 'Thu gọn',
    'Collapse All' => 'Thu gọn toàn bộ',
    'Comma Separated Values' => 'Dấu phẩy ngăn cách các giá trị',
    'Excel' => '',
    'Expand' => 'Mở rộng',
    'Expand All' => 'Mở rộng toàn bộ',
    'Export All Data' => 'Trích xuất toàn bộ dữ liệu',
    'Failed to update editable data due to an unknown server error' => 'Có lỗi máy chủ khi chỉnh sửa các giá trị có thể thay đổi',
    'Generated' => 'Đã khởi tạo',
    'Generating the export file. Please wait...' => 'Đang khởi tạo tệp trích xuất. Vui lòng chờ...',
    'Grid Export' => 'Trích xuất',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Invalid editable index or model form name' => 'Vị trí sửa hoặc tên của mẫu đơn không hợp lệ',
    'Invalid or bad editable data' => 'Dữ liệu sửa không hợp lệ',
    'JSON' => '',
    'JavaScript Object Notation' => '',
    'Microsoft Excel 95+' => '',
    'No valid editable model found' => 'Không tìm thấy mẫu sửa hợp lệ nào',
    'Ok to proceed?' => 'Chọn OK để tiếp tục?',
    'PDF' => '',
    'PDF export generated by kartik-v/yii2-grid extension' => 'PDF được trích xuất bởi bản mở rộng kartik-v/yii2-grid',
    'Page' => 'Trang',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Yêu cầu đã được thực hiện! Bạn có thể đóng thông báo này sau khi lưu thành công tệp đã tải về.',
    'Show all data' => 'Xem toàn bộ dữ liệu',
    'Show first page data' => 'Xem trang đầu tiên',
    'Tab Delimited Text' => '',
    'Text' => '',
    'The JSON export file will be generated for download.' => 'Tệp JSON sẽ được khởi tạo để tải về.',
    'The PDF export file will be generated for download.' => 'Tệp PDF sẽ được khởi tạo để tải về.',
    'There are {totalCount} records. Are you sure you want to display them all?' => 'Có {totalCount} bản ghi. Bạn có chắc là muốn hiển thị toàn bộ?',
    'Yii2 Grid Export (PDF)' => '',
    'export' => 'trích xuất',
    'grid-export' => '',
    'krajee, grid, export, yii2-grid, pdf' => '',
    '© Krajee Yii2 Extensions' => '',
    'Actions' => 'Hành động',
    'Active' => 'Kích hoạt',
    'Add Book' => 'Thêm sách',
    'Are you sure to delete this item?' => 'Bạn có chắc là sẽ xóa mục này không?',
    'Book Listing' => 'Liệt kê sách',
    'Delete' => 'Xóa',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Tắt các trình chặn popup trong trình duyệt để việc tải về được suôn sẻ.',
    'Download Selected' => 'Tải về mục đã chọn',
    'Export' => 'Trích xuất',
    'Export Page Data' => 'Trích xuất dữ liệu trang',
    'ExportWorksheet' => 'Trích xuất bảng tính',
    'Inactive' => 'Không kích hoạt',
    'Library' => 'Thư viện',
    'No data found' => 'Không tìm thấy dữ liệu',
    'Reset Grid' => 'Thiết lập lại',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Thay đổi kích thước cột bảng giống như một bảng tính bằng cách kéo các cạnh cột.',
    'The CSV export file will be generated for download.' => 'Tập tin CSV sẽ được trích xuất để tải về.',
    'The EXCEL export file will be generated for download.' => 'Tập tin EXCEL sẽ được trích xuất để tải về.',
    'The HTML export file will be generated for download.' => 'Tập tin HTML sẽ được trích xuất để tải về.',
    'The TEXT export file will be generated for download.' => 'Tập tin TEXT sẽ được trích xuất để tải về.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Hiển thị tổng cho các giá trị 3 cột đầu và trung bình cộng cho cột cuối.',
    'The table header sticks to the top in this demo as you scroll' => 'Trong bản giới thiệu này, tiêu đề của bảng luôn được hiển thị phía trên khi trang được cuộn xuống',
    'Update' => 'Sửa',
    'View' => 'Xem',
];
