<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'View'=>'',
    'Update'=>'',
    'Delete'=>'',
    'Are you sure to delete this item?'=>'',
    'Actions'=>'',
    'HTML' => '',
    'CSV' => '',
    'Text' => '',
    'Excel' => '',
    'Save as HTML' => '',
    'Save as CSV' => '',
    'Save as Text' => '',
    'Save as Excel' => '',
    'Active' => '',
    'Inactive' => '',
    'Export' => '',
    'export' => '',
    'grid-export' => '',
    'The HTML export file will be generated for download.' => '',
    'The CSV export file will be generated for download.' => '',
    'The TEXT export file will be generated for download.' => '',
    'The EXCEL export file will be generated for download.' => '',
    'Disable any popup blockers in your browser to ensure proper download.' => '',
    'No data found' => '',
    // Demo data
    'Library' => '',
    'Book Listing' => '',
    'Add Book' => '',
    'Reset Grid' => '',
    'Download Selected' => '',
    'The table header sticks to the top in this demo as you scroll' => '',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => '',
];
