<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
	'Export Data' => '',
	'Save as HTML' => '',
	'Save as CSV' => '',
	'Save as Excel' => '',
	'Active' => '',
	'Inactive' => '',
	'Actions' => '',
	'export' => '',
    'HTML export file will be generated. The exported file needs to be saved as .htm/.html extension. You can also save it as .xls extension to view as an excel spreasheet.' => '',
    'CSV export file will be generated. The exported file needs to be saved as .csv/.txt extension.' => '',
    'CExcel export file will be generated. The exported file needs to be saved as .xls/.xlsx extension.' => '',
);
