<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'View'=>'Bekijken',
    'Update'=>'Bewerken',
    'Delete' => 'Verwijderen',
    'Are you sure you want to delete this item?' => 'Weet je zeker dat je dit item wilt verwijderen?',
    'Actions'=>'Acties',
    'HTML' => 'HTML',
    'CSV' => 'CSV',
    'Text' => 'Tekst',
    'Excel' => 'Excel',
    'Save as HTML' => 'Als HTML opslaan',
    'Save as CSV' => 'Als CSV opslaan',
    'Save as Text' => 'Als Tekst opslaan',
    'Save as Excel' => 'Als Excel opslaan',
    'Active' => 'Actief',
    'Inactive' => 'Inactief',
    'Export' => 'Exporteren',
    'export' => '',
    'grid-export' => '',
    'The HTML export file will be generated for download.' => 'Het HTML exportbestand wordt voor download gegenereerd.',
    'The CSV export file will be generated for download.' => 'Het CSV exportbestand wordt voor download gegenereerd.',
    'The TEXT export file will be generated for download.' => 'Het Tekst exportbestand wordt voor download gegenereerd.',
    'The EXCEL export file will be generated for download.' => 'Het Excel exportbestand wordt voor download gegenereerd.',
    'Disable any popup blockers in your browser to ensure proper download.' => 'De-aktiveer mogelijk aanwezige popup-blockers in uw browser zodat de download werkt.',
    'No data found' => 'Geen data gevonden',
    // Demo data
    'Library' => 'Bibliotheek',
    'Book Listing' => 'Boekenlijst',
    'Add Book' => 'Nieuw boek',
    'Reset Grid' => '',
    'Download Selected' => 'geselecteerde downloaden',
    'The table header sticks to the top in this demo as you scroll' => 'Als u scrollt, blijft de tabelkop bovenaan in de demo.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'De pagina-samenvatting laat SUM voor de eerste 3 kolommen en AVG voor de laatste zien.'
];
