<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Działania',
    'Active' => 'Aktywny',
    'Add Book' => 'Dodaj książkę',
    'All' => '',
    'Are you sure to delete this item?' => 'Czy na pewno usunąć?',
    'Book Listing' => 'Lista książek',
    'CSV' => '',
    'Clear selection' => '',
    'Collapse All' => '',
    'Collapse' => '',
    'Comma Separated Values' => '',
    'Delete' => 'Usuń',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Aby pobrać dane, odblokuj wyskakujące okienka',
    'Download Selected' => 'Pobierz zaznaczone',
    'Excel' => '',
    'Expand All' => '',
    'Expand' => '',
    'Export All Data' => '',
    'Export Page Data' => 'Eksport Page Danych',
    'Export' => 'Eksportuj',
    'ExportWorksheet' => 'EksportérArkusz',
    'Generated' => '',
    'Generating the export file. Please wait...' => '',
    'Grid Export' => '',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Inactive' => 'Nieaktywny',
    'Invalid editable index or model form name' => '',
    'Invalid or bad editable data' => '',
    'JSON' => '',
    'JavaScript Object Notation' => '',
    'Library' => 'Biblioteka',
    'Microsoft Excel 95+' => '',
    'No data found' => 'Brak danych',
    'No valid editable model found' => '',
    'Ok to proceed?' => '',
    'PDF export generated by kartik-v/yii2-grid extension' => '',
    'PDF' => '',
    'Page' => '',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => '',
    'Reset Grid' => 'Zresetuj',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Zmiana rozmiaru kolumny tabeli, tak jak w arkuszu kalkulacyjnym, przeciągając krawędzie kolumn.',
    'Show all data' => '',
    'Show first page data' => '',
    'Tab Delimited Text' => '',
    'Text' => 'Plik tekstowy',
    'The CSV export file will be generated for download.' => 'Pobieranie danych w postaci pliku CSV',
    'The EXCEL export file will be generated for download.' => 'Pobieranie danych w postaci pliku Excel',
    'The HTML export file will be generated for download.' => 'Pobieranie danych w postaci pliku HTML',
    'The JSON export file will be generated for download.' => '',
    'The PDF export file will be generated for download.' => '',
    'The TEXT export file will be generated for download.' => 'Pobieranie danych w postaci pliku tekstowego',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Stopka tabeli zawiera sumę każdej trzech pierwszych kolumn i średnią ostaniej',
    'The table header sticks to the top in this demo as you scroll' => '',
    'There are {totalCount} records. Are you sure you want to display them all?' => '',
    'Update' => 'Edytuj',
    'View' => 'Zobacz',
    'Yii2 Grid Export (PDF)' => '',
    'export' => 'eksportuj',
    'grid-export' => 'eksportowanie tabeli',
    'krajee, grid, export, yii2-grid, pdf' => '',
    '© Krajee Yii2 Extensions' => '',
];
