<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure to delete this {item}?' => 'Czy na pewno {item}?',
    'CSV' => '',
    'Collapse' => '',
    'Collapse All' => '',
    'Comma Separated Values' => '',
    'Excel' => '',
    'Expand' => '',
    'Failed to update editable data due to an unknown server error' => '',
    'Generated' => '',
    'Generating the export file. Please wait...' => '',
    'Grid Export' => '',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Invalid editable index or model form name' => '',
    'Invalid or bad editable data' => '',
    'JSON' => '',
    'JavaScript Object Notation' => '',
    'Microsoft Excel 95+' => '',
    'No valid editable model found' => '',
    'PDF' => '',
    'PDF export generated by kartik-v/yii2-grid extension' => '',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => '',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.'  =>  'Wyświetlone <b>{begin, number}-{end, number}</b> z <b>{totalCount, number}</b> {totalCount, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'Tab Delimited Text' => '',
    'The JSON export file will be generated for download.' => '',
    'The table header sticks to the top in this demo as you scroll' => '',
    'There are {totalCount} records. Are you sure you want to display them all?' => '',
    'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => 'Razem <b>{count, number}</b> {count, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'Yii2 Grid Export (PDF)' => '',
    'item' => 'rekord',
    'items' => 'rekordu',
    'items-few' => 'rekordów',
    'items-many' => 'rekordów',
    'krajee, grid, export, yii2-grid, pdf' => '',
    '© Krajee Yii2 Extensions' => '',
    'Actions' => 'Działania',
    'Active' => 'Aktywny',
    'Add Book' => 'Dodaj książkę',
    'All' => 'Wyświetl wszystko',
    'Book Listing' => 'Lista książek',
    'Clear selection' => 'Wyczyść zaznaczenie',
    'Delete' => 'Usuń',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Aby pobrać dane, odblokuj wyskakujące okienka',
    'Download Selected' => 'Pobierz zaznaczone',
    'Expand All' => 'Rozwiń wszystko',
    'Export' => 'Eksportuj',
    'Export All Data' => 'Eksportuj wszystkie dane',
    'Export Page Data' => 'Eksport widocznych danych',
    'ExportWorksheet' => 'Eksportuj arkusz',
    'Inactive' => 'Nieaktywny',
    'Library' => 'Biblioteka',
    'No data found' => 'Brak danych',
    'Ok to proceed?' => 'Kliknij Ok aby kontynuować',
    'Page' => 'Z podziałem na strony',
    'Reset Grid' => 'Zresetuj',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Zmiana rozmiaru kolumny tabeli, tak jak w arkuszu kalkulacyjnym, przeciągając krawędzie kolumn.',
    'Show all data' => 'Wyświetl wszystkie dane bez stronicowania',
    'Show first page data' => 'Wyświetl ze stronicowaniem',
    'Text' => 'Plik tekstowy',
    'The CSV export file will be generated for download.' => 'Pobieranie danych w postaci pliku CSV',
    'The EXCEL export file will be generated for download.' => 'Pobieranie danych w postaci pliku Excel',
    'The HTML export file will be generated for download.' => 'Pobieranie danych w postaci pliku HTML',
    'The PDF export file will be generated for download.' => 'Plik PDF zostanie wygenerowany do pobrania',
    'The TEXT export file will be generated for download.' => 'Pobieranie danych w postaci pliku tekstowego',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Stopka tabeli zawiera sumę każdej trzech pierwszych kolumn i średnią ostaniej',
    'Update' => 'Edytuj',
    'View' => 'Zobacz',
    'export' => 'eksportuj',
    'grid-export' => 'eksportowanie tabeli',
];
