<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'View'=>'Zobacz',
    'Update'=>'Edytuj',
    'Delete'=>'Usuń',
    'Are you sure to delete this item?'=>'Czy na pewno usunąć?',
    'Actions'=>'Działania',
    'HTML' => '',
    'CSV' => '',
    'Text' => 'Plik tekstowy',
    'Excel' => '',
    'Save as HTML' => 'Zapisz jako plik HTML',
    'Save as CSV' => 'Zapisz jako plik CSV',
    'Save as Text' => 'Zapisz jako plik tekstowy',
    'Save as Excel' => 'Zapisz jako plik Excel',
    'Active' => 'Aktywny',
    'Inactive' => 'Nieaktywny',
    'Export' => 'Eksportuj',
    'ExportWorksheet' => 'EksportérArkusz',
    'Export Page Data'=>'Eksport Page Danych',
    'export' => 'eksportuj',
    'grid-export' => 'eksportowanie tabeli',
    'The HTML export file will be generated for download.' => 'Pobieranie danych w postaci pliku HTML',
    'The CSV export file will be generated for download.' => 'Pobieranie danych w postaci pliku CSV',
    'The TEXT export file will be generated for download.' => 'Pobieranie danych w postaci pliku tekstowego',
    'The EXCEL export file will be generated for download.' => 'Pobieranie danych w postaci pliku Excel',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Aby pobrać dane, odblokuj wyskakujące okienka',
    'No data found' => 'Brak danych',
    // Demo data
    'Library' => 'Biblioteka',
    'Book Listing' => 'Lista książek',
    'Add Book' => 'Dodaj książkę',
    'Reset Grid' => 'Zresetuj',
    'Download Selected' => 'Pobierz zaznaczone',
    'The table header sticks to the top in this demo as you scroll' => '',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Stopka tabeli zawiera sumę każdej trzech pierwszych kolumn i średnią ostaniej',
];
