<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'View' => 'Megtekintés',
    'Update' => 'Módosítás',
    'Delete' => 'Törlés',
    'Are you sure to delete this item?' => 'Biztosan törölni szeretnéd ezt az elemet?',
    'Actions' => 'Műveletek',
    'HTML' => 'HTML',
    'CSV' => 'CSV',
    'Text' => 'Szöveges',
    'Excel' => 'Excel',
    'Save as HTML' => 'Mentés HTML-ként',
    'Save as CSV' => 'Mentés CSV-ként',
    'Save as Text' => 'Mentés Szövegként',
    'Save as Excel' => 'Mentés Excelként',
    'Active' => 'Aktív',
    'Inactive' => 'Inaktív',
    'Export' => 'Exportálás',
    'export' => 'exportálás',
    'grid-export' => 'grid-exportalas',
    'The HTML export file will be generated for download.' => 'A HTML export fájl előkészítése letöltésre.',
    'The CSV export file will be generated for download.' => 'A CSV export fájl előkészítése letöltésre.',
    'The TEXT export file will be generated for download.' => 'A Szöveges export fájl előkészítése letöltésre.',
    'The EXCEL export file will be generated for download.' => 'Az EXCEL export fájl előkészítése letöltésre.',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Kapcsoljon ki minden felugró ablak blokkolót a böngészőjében a sikeres letöltés érdekében.',
    'No data found' => 'Adat nem található',
    // Demo data
    'Library' => 'Könyvtár',
    'Book Listing' => 'Könyvek listázása',
    'Add Book' => 'Könyv hozzáadása',
    'Reset Grid' => 'Táblázat alaphelyzetbe állítása',
    'Download Selected' => 'Kiválasztottak letöltése',
    'The table header sticks to the top in this demo as you scroll' => 'A táblázat fejléce az oldal tetejéhez lesz igazítva a görgetés során',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Az oldal összesítő az első 3 érték oszlop összegét és az utolsó átlagát jeleníti meg.',
];
?>
