<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Műveletek',
    'Active' => 'Aktív',
    'Add Book' => 'Könyv hozzáadása',
    'All' => 'Összes',
    'Are you sure to delete this item?' => 'Biztosan törölni szeretnéd ezt az elemet?',
    'Book Listing' => 'Könyvek listázása',
    'CSV' => 'CSV',
    'Clear selection' => '',
    'Collapse All' => '',
    'Collapse' => '',
    'Comma Separated Values' => 'Vesszővel elválasztott értékek',
    'Delete' => 'Törlés',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Kapcsoljon ki minden felugró ablak blokkolót a böngészőjében a sikeres letöltés érdekében.',
    'Download Selected' => 'Kiválasztottak letöltése',
    'Excel' => 'Excel',
    'Expand All' => '',
    'Expand' => '',
    'Export All Data' => 'Összes Adat Export',
    'Export Page Data' => 'Aktuális Oldal Export',
    'Export' => 'Exportálás',
    'ExportWorksheet' => 'MunkalapExport',
    'Generated' => 'Generálva',
    'Generating the export file. Please wait...' => 'Export fájl előkészítése letöltésre. Kérlek várj...',
    'Grid Export' => 'Táblázat exportálása',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => '',
    'Inactive' => 'Inaktív',
    'Invalid editable index or model form name' => '',
    'Invalid or bad editable data' => '',
    'JSON' => '',
    'JavaScript Object Notation' => '',
    'Library' => 'Könyvtár',
    'Microsoft Excel 95+' => '',
    'No data found' => 'Adat nem található',
    'No valid editable model found' => '',
    'Ok to proceed?' => 'Biztos, hogy folytatod?',
    'PDF export generated by kartik-v/yii2-grid extension' => 'PDF export generálva kartik-v/yii2-grid kiegészítő által',
    'PDF' => '',
    'Page' => 'Oldal',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Kérelem elküldve! Letöltés után az ablakot nyugodtan bezárhatod.',
    'Reset Grid' => 'Táblázat alaphelyzetbe állítása',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Átméretezni az oszlopokat, mint egy táblázatkezelő húzza az oszlop élek.',
    'Show all data' => 'Összes adat mutata',
    'Show first page data' => 'Első oldal adat mutat',
    'Tab Delimited Text' => 'Tabulátorral tagolt szöveg',
    'Text' => 'Szöveges',
    'The CSV export file will be generated for download.' => 'A CSV export fájl előkészítése letöltésre.',
    'The EXCEL export file will be generated for download.' => 'Az EXCEL export fájl előkészítése letöltésre.',
    'The HTML export file will be generated for download.' => 'A HTML export fájl előkészítése letöltésre.',
    'The JSON export file will be generated for download.' => 'A JSON export fájl előkészítése a letöltésre.',
    'The PDF export file will be generated for download.' => 'A PDF export fájl előkészítése a letöltésre.',
    'The TEXT export file will be generated for download.' => 'A Szöveges export fájl előkészítése letöltésre.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Az oldal összesítő az első 3 érték oszlop összegét és az utolsó átlagát jeleníti meg.',
    'The table header sticks to the top in this demo as you scroll' => 'A táblázat fejléce az oldal tetejéhez lesz igazítva a görgetés során',
    'There are {totalCount} records. Are you sure you want to display them all?' => '',
    'Update' => 'Módosítás',
    'View' => 'Megtekintés',
    'Yii2 Grid Export (PDF)' => 'Yii2 Táblázat Export (PDF)',
    'export' => 'exportálás',
    'grid-export' => 'grid-exportalas',
    'krajee, grid, export, yii2-grid, pdf' => '',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Kiegészítők',
];
