<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'פעולות',
    'Active' => 'פעיל',
    'Add Book' => '',
    'All' => 'הכל',
    'Are you sure to delete this item?' => 'האם למחוק רשומה?',
    'Book Listing' => '',
    'CSV' => '',
    'Clear selection' => 'ביטול בחירה',
    'Collapse' => 'צמצום',
    'Collapse All' => 'צמצום הכל',
    'Comma Separated Values' => '',
    'Delete' => 'מחיקה',
    'Disable any popup blockers in your browser to ensure proper download.' => 'יש להשבית חוסמי פופ-אפים דפדפן כדי להבטיח הורדה תקינה של הקובץ.',
    'Download Selected' => 'הורדה',
    'Excel' => '',
    'Expand' => 'הרחבה',
    'Expand All' => 'הרחבת הכל',
    'Export' => 'ייצוא',
    'Export All Data' => 'ייצוא כל המידע',
    'Export Page Data' => 'ייצוא הרשומות המוצגות',
    'ExportWorksheet' => '',
    'Failed to update editable data due to an unknown server error' => '',
    'Generated' => '',
    'Generating the export file. Please wait...' => 'מייצא קובץ, אנא המתן...',
    'Grid Export' => 'ייצוא טבלה',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Inactive' => 'לא-פעיל',
    'Invalid editable index or model form name' => '',
    'Invalid or bad editable data' => '',
    'JSON' => '',
    'JavaScript Object Notation' => '',
    'Library' => '',
    'Microsoft Excel 95+' => '',
    'No data found' => 'אין רשומות',
    'No valid editable model found' => '',
    'Ok to proceed?' => 'להמשיך?',
    'PDF' => '',
    'PDF export generated by kartik-v/yii2-grid extension' => '',
    'Page' => 'עמוד',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => '',
    'Reset Grid' => 'אתחול טבלה',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => '',
    'Show all data' => 'הצגת כל הרשומות',
    'Show first page data' => 'הצג רשומות של העמוד הראשון',
    'Tab Delimited Text' => '',
    'Text' => '',
    'The CSV export file will be generated for download.' => '',
    'The EXCEL export file will be generated for download.' => '',
    'The HTML export file will be generated for download.' => '',
    'The JSON export file will be generated for download.' => '',
    'The PDF export file will be generated for download.' => '',
    'The TEXT export file will be generated for download.' => '',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => '',
    'The table header sticks to the top in this demo as you scroll' => '',
    'There are {totalCount} records. Are you sure you want to display them all?' => '',
    'Update' => 'עדכון',
    'View' => 'תצוגה',
    'Yii2 Grid Export (PDF)' => '',
    'export' => '',
    'grid-export' => '',
    'krajee, grid, export, yii2-grid, pdf' => '',
    '© Krajee Yii2 Extensions' => '',
];
