<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All' => '',
    'Clear selection' => '',
    'Collapse' => '',
    'Collapse All' => '',
    'Comma Separated Values' => '',
    'Expand' => '',
    'Expand All' => '',
    'Export All Data' => '',
    'Generated' => '',
    'Generating the export file. Please wait...' => '',
    'Grid Export' => '',
    'Hyper Text Markup Language' => '',
    'JSON' => '',
    'JavaScript Object Notation' => '',
    'Microsoft Excel 95+' => '',
    'Ok to proceed?' => '',
    'PDF' => '',
    'PDF export generated by kartik-v/yii2-grid extension' => '',
    'Page' => '',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => '',
    'Show all data' => '',
    'Show first page data' => '',
    'Tab Delimited Text' => '',
    'The JSON export file will be generated for download.' => '',
    'The PDF export file will be generated for download.' => '',
    'Yii2 Grid Export (PDF)' => '',
    'krajee, grid, export, yii2-grid, pdf' => '',
    '© Krajee Yii2 Extensions' => '',
    'Actions' => 'Handlinger',
    'Active' => 'Aktiv',
    'Add Book' => 'Tilføj Bog',
    'Are you sure to delete this item?' => 'Er du sikker på at du vil slette dette element?',
    'Book Listing' => 'Bogoversigt',
    'CSV' => 'CSV',
    'Delete' => 'Slet',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Deaktivér eventuelle popup blockers i din browser for at sikre korrekt download.',
    'Download Selected' => 'Download Valgte',
    'Excel' => 'Excel',
    'Export' => 'Eksportér',
    'Export Page Data' => 'Export Side Data',
    'ExportWorksheet' => 'EksportérArbejdsark',
    'HTML' => 'HTML',
    'Inactive' => 'Inaktiv',
    'Library' => 'Bibliotek',
    'No data found' => 'Ingen data fundet',
    'Reset Grid' => 'Nulstil Tabel',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Resize tabelkolonner ligesom et regneark ved at trække kolonnen kanter.',
    'Text' => 'Tekst',
    'The CSV export file will be generated for download.' => 'CSV eksportfilen vil blive genereret til download.',
    'The EXCEL export file will be generated for download.' => 'EXCEL eksportfilen vil blive genereret til download.',
    'The HTML export file will be generated for download.' => 'HTML eksportfilen vil blive genereret til download.',
    'The TEXT export file will be generated for download.' => 'TEKST eksportfilen vil blive genereret til download.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Sideresuméet viser SUM for de første 3 kolonner og AVG for den sidste.',
    'The table header sticks to the top in this demo as you scroll' => 'Tabeloverskriften fastgøres til toppen i denne demo, når du scroller',
    'Update' => 'Opdatér',
    'View' => 'Vis',
    'export' => 'exportér',
    'grid-export' => 'tabel-eksport',
];
