<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'View' => 'Vis',
    'Update' => 'Opdatér',
    'Delete' => 'Slet',
    'Are you sure to delete this item?' => 'Er du sikker på at du vil slette dette element?',
    'Actions' => 'Handlinger',
    'HTML' => 'HTML',
    'CSV' => 'CSV',
    'Text' => 'Tekst',
    'Excel' => 'Excel',
    'Save as HTML' => 'Gem som HTML',
    'Save as CSV' => 'Gem som CSV',
    'Save as Text' => 'Gem som Tekst',
    'Save as Excel' => 'Gem som Excel',
    'Active' => 'Aktiv',
    'Inactive' => 'Inaktiv',
    'Export' => 'Eksportér',
    'export' => 'exportér',
    'grid-export' => 'tabel-eksport',
    'The HTML export file will be generated for download.' => 'HTML eksportfilen vil blive genereret til download.',
    'The CSV export file will be generated for download.' => 'CSV eksportfilen vil blive genereret til download.',
    'The TEXT export file will be generated for download.' => 'TEKST eksportfilen vil blive genereret til download.',
    'The EXCEL export file will be generated for download.' => 'EXCEL eksportfilen vil blive genereret til download.',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Deaktivér eventuelle popup blockers i din browser for at sikre korrekt download.',
    'No data found' => 'Ingen data fundet',
    // Demo data
    'Library' => 'Bibliotek',
    'Book Listing' => 'Bogoversigt',
    'Add Book' => 'Tilføj Bog',
    'Reset Grid' => 'Nulstil Tabel',
    'Download Selected' => 'Download Valgte',
    'The table header sticks to the top in this demo as you scroll' => 'Tabeloverskriften fastgøres til toppen i denne demo, når du scroller',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Sideresuméet viser SUM for de første 3 kolonner og AVG for den sidste.',
];
